fn main() {
    // Windows AI bindings are generated by build-cross.py using windows-bindgen
    // See generate_windows_ai_bindings() in build-cross.py
    //
    // The generated bindings are at src/windows_ai_bindings.rs and provide:
    // - Microsoft.Windows.AI.AIFeatureReadyState enum
    // - Microsoft.Windows.AI.Text.LanguageModel class
    // - Microsoft.Windows.AI.Text.LanguageModelResponse class
    // - etc.
    //
    // These APIs require:
    // - AI Dev Gallery installed (provides Windows App SDK AI runtime)
    // - App packaged as MSIX with systemAIModels capability

    tauri_build::build()
}
