fn main() {
    // Windows AI bindings are generated by build-cross.py using windows-bindgen
    // See generate_windows_ai_bindings() in build-cross.py
    //
    // The generated bindings are at src/windows_ai_bindings.rs and provide:
    // - Microsoft.Windows.AI.AIFeatureReadyState enum
    // - Microsoft.Windows.AI.Text.LanguageModel class
    // - Microsoft.Windows.AI.Text.LanguageModelResponse class
    // - etc.
    //
    // These APIs require package identity + the systemAIModels capability:
    // either full MSIX packaging, or a sparse identity package registered with
    // Add-AppxPackage -ExternalLocation (build-cross.py build-sparse). The
    // custom application manifest below embeds the <msix> element that ties a
    // directly-launched loose exe to that sparse identity.
    let attributes = tauri_build::Attributes::new().windows_attributes(
        tauri_build::WindowsAttributes::new().app_manifest(include_str!("windows-app.manifest")),
    );
    tauri_build::try_build(attributes).expect("failed to run tauri-build");
}
