[req]
distinguished_name = req_distinguished_name
x509_extensions = v3_req
prompt = no

[req_distinguished_name]
C = US
ST = NY
L = New York
O = WindowsForum Fara Technologies LLC
OU = IT Department
CN = WindowsForum Fara Technologies LLC IT Department

[v3_req]
keyUsage = digitalSignature
extendedKeyUsage = codeSigning
