//! UI-framework-neutral Windows AI/Phi Silica runtime.
//!
//! This crate is the single owner of `WFDiag`'s package-identity gate, Limited
//! Access Feature handling, Windows AI activation fallback, model cache, and
//! generation path. UI shells consume the typed provider-status adapter or
//! the explicit runtime functions; neither path depends on Tauri or `WebView2`.

#![allow(clippy::missing_errors_doc)]

use serde::Serialize;
#[cfg(windows)]
use std::time::{SystemTime, UNIX_EPOCH};

// Generated by windows-bindgen — never hand-edited, so its pedantic findings
// are silenced here at the module declaration instead of inside the file.
#[cfg(windows)]
#[rustfmt::skip]
#[allow(unsafe_code)]
#[allow(
    clippy::borrow_as_ptr,
    clippy::ptr_as_ptr,
    clippy::redundant_closure_for_method_calls,
    clippy::transmute_ptr_to_ptr
)]
mod windows_ai_bindings;

// WinRT/COM work lives here; unsafe is scoped to this module and the
// package-identity probe below.
#[allow(unsafe_code)]
mod runtime;

pub use runtime::{
    PhiPromptFit, PhiSilicaAnalysisResponse, PhiSilicaStatus, ensure_phi_silica_ready,
    generate_response, is_phi_silica_available, measure_prompt_fit,
};

use wfdiag_native_ai_chat::{
    ChatProvider, ChatRequest, ChatTurn, FinishReason, flatten_chat_request,
};
use wfdiag_native_ai_provider::{BackendFuture, PhiStatusSnapshot, PhiStatusSource};

/// Provider-neutral chat adapter over the package-aware Phi runtime.
///
/// Phi exposes a single prompt rather than a message/tool API. The shared
/// chat engine already constrains its context budget and disables tools, so
/// this adapter only flattens the retained conversation and emits the one
/// completed response as a delta. Both desktop shells can therefore select
/// Phi through the same [`ChatProvider`] boundary as network providers.
///
/// `is_cancelled` answers whether the caller's turn-level cancellation has
/// fired. The shared engine's `select!` already returns a "Cancelled" turn to
/// the UI the instant that happens, regardless of this adapter, but
/// forwarding the check into `generate_response` is what lets the abandoned
/// generation actually release the process-wide model mutex early instead of
/// idling out its full budget. It's a plain closure rather than
/// `tokio_util::sync::CancellationToken` so this crate doesn't need that
/// dependency: construct with [`PhiChatProvider::new`] and
/// `move || token.is_cancelled()` when a real turn token is available;
/// `Default` never cancels, for callers (like report/analysis one-shots)
/// with no per-turn cancellation to forward yet.
#[derive(Clone)]
pub struct PhiChatProvider {
    is_cancelled: std::sync::Arc<dyn Fn() -> bool + Send + Sync>,
}

impl std::fmt::Debug for PhiChatProvider {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.debug_struct("PhiChatProvider").finish_non_exhaustive()
    }
}

impl Default for PhiChatProvider {
    fn default() -> Self {
        Self {
            is_cancelled: std::sync::Arc::new(|| false),
        }
    }
}

impl PhiChatProvider {
    #[must_use]
    pub fn new(is_cancelled: impl Fn() -> bool + Send + Sync + 'static) -> Self {
        Self {
            is_cancelled: std::sync::Arc::new(is_cancelled),
        }
    }
}

impl ChatProvider for PhiChatProvider {
    fn stream<'a>(
        &'a self,
        request: &'a ChatRequest,
        tx: tokio::sync::mpsc::Sender<String>,
    ) -> std::pin::Pin<Box<dyn std::future::Future<Output = Result<ChatTurn, String>> + Send + 'a>>
    {
        Box::pin(async move {
            let is_cancelled = self.is_cancelled.clone();
            let text =
                generate_response(&flatten_chat_request(request), move || is_cancelled()).await?;
            let _ = tx.send(text.clone()).await;
            Ok(ChatTurn {
                text,
                tool_calls: Vec::new(),
                finished: FinishReason::Stop,
                actual_models: Vec::new(),
                provider_replay: None,
            })
        })
    }
}

/// Real package-identity/LAF-aware status source shared by Tauri and Reactor.
#[derive(Debug, Clone, Copy, Default)]
pub struct WindowsPhiStatusSource;

impl PhiStatusSource for WindowsPhiStatusSource {
    fn probe(&self) -> BackendFuture<'_, PhiStatusSnapshot> {
        Box::pin(async {
            match probe_phi_silica_status().await {
                Ok(status) => PhiStatusSnapshot {
                    available: status.available,
                    ready: status.ready_state.as_deref() == Some("Ready"),
                    message: Some(status.message),
                },
                Err(error) => PhiStatusSnapshot {
                    available: false,
                    ready: false,
                    message: Some(error),
                },
            }
        })
    }
}

/// Run the blocking `WinRT` availability probe off the async runtime worker.
pub async fn probe_phi_silica_status() -> Result<PhiSilicaStatus, String> {
    tokio::task::spawn_blocking(is_phi_silica_available)
        .await
        .map_err(|error| format!("Phi Silica availability check task panicked: {error}"))
}

/// True when the current process has registered package identity.
///
/// The runtime checks this before initializing `WinRT`, loading Windows App SDK
/// DLLs, or attempting LAF unlock. A loose executable therefore never reaches
/// the Windows AI activation path.
#[cfg(windows)]
#[must_use]
#[allow(unsafe_code)] // one Win32 call: package identity probe
pub fn has_package_identity() -> bool {
    use windows::Win32::Foundation::ERROR_INSUFFICIENT_BUFFER;
    use windows::Win32::Storage::Packaging::Appx::GetCurrentPackageFullName;

    let mut length = 0;
    let result = unsafe { GetCurrentPackageFullName(&raw mut length, None) };
    result == ERROR_INSUFFICIENT_BUFFER
}

#[cfg(not(windows))]
#[must_use]
pub const fn has_package_identity() -> bool {
    false
}

#[derive(Debug, Serialize)]
#[serde(tag = "type", content = "details")]
enum PhiError {
    #[cfg(windows)]
    AiUnavailable { provider: String, reason: String },
    #[cfg(not(windows))]
    PlatformNotSupported { operation: String },
}

impl PhiError {
    #[cfg(windows)]
    fn ai_unavailable(provider: impl Into<String>, reason: impl Into<String>) -> Self {
        Self::AiUnavailable {
            provider: provider.into(),
            reason: reason.into(),
        }
    }
}

impl From<PhiError> for String {
    fn from(error: PhiError) -> Self {
        serde_json::to_string(&error).unwrap_or_else(|_| "Phi Silica operation failed".to_string())
    }
}

#[cfg(windows)]
fn format_log_time(time: SystemTime) -> String {
    let seconds = time
        .duration_since(UNIX_EPOCH)
        .unwrap_or_default()
        .as_secs();
    format!(
        "{:02}:{:02}:{:02}",
        (seconds / 3600) % 24,
        (seconds % 3600) / 60,
        seconds % 60
    )
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn non_windows_identity_is_false() {
        #[cfg(not(windows))]
        assert!(!has_package_identity());
    }

    #[test]
    fn chat_adapter_keeps_history_and_current_question() {
        let request = ChatRequest {
            system: Some("Use only supplied evidence.".to_string()),
            messages: vec![
                wfdiag_native_ai_chat::ChatMessage::user("Is my disk healthy?"),
                wfdiag_native_ai_chat::ChatMessage::assistant("I need more evidence."),
                wfdiag_native_ai_chat::ChatMessage::user("Current free space is 8%."),
            ],
            tools: Vec::new(),
            max_tokens: None,
        };
        let prompt = flatten_chat_request(&request);
        assert!(prompt.starts_with("Use only supplied evidence."));
        assert!(prompt.contains("User: Is my disk healthy?"));
        assert!(prompt.contains("Assistant: I need more evidence."));
        assert!(prompt.contains("User: Current free space is 8%."));
        assert!(prompt.ends_with("Assistant:"));
    }

    #[cfg(not(windows))]
    #[test]
    fn provider_adapter_projects_the_platform_status() {
        let runtime = tokio::runtime::Builder::new_current_thread()
            .build()
            .expect("test runtime");
        let status = runtime.block_on(WindowsPhiStatusSource.probe());

        assert!(!status.available);
        assert!(!status.ready);
        assert_eq!(
            status.message.as_deref(),
            Some("Phi Silica is only available on Windows")
        );
    }

    #[cfg(windows)]
    #[test]
    fn error_wire_shape_remains_compatible() {
        let encoded: String = PhiError::ai_unavailable("phi_silica", "not ready").into();
        assert_eq!(
            serde_json::from_str::<serde_json::Value>(&encoded).unwrap(),
            serde_json::json!({
                "type": "AiUnavailable",
                "details": { "provider": "phi_silica", "reason": "not ready" }
            })
        );
    }
}
