//! UI-framework-neutral Windows AI/Phi Silica runtime.
//!
//! This crate is the single owner of `WFDiag`'s package-identity gate, Limited
//! Access Feature handling, Windows AI activation fallback, model cache, and
//! generation path. UI shells consume the typed provider-status adapter or
//! the explicit runtime functions; neither path depends on Tauri or `WebView2`.

#![allow(clippy::missing_errors_doc)]

#[cfg(windows)]
use std::time::{SystemTime, UNIX_EPOCH};

// Generated by windows-bindgen — never hand-edited, so its pedantic findings
// are silenced here at the module declaration instead of inside the file.
#[cfg(windows)]
#[rustfmt::skip]
#[allow(unsafe_code)]
#[allow(
    clippy::borrow_as_ptr,
    clippy::ptr_as_ptr,
    clippy::redundant_closure_for_method_calls,
    clippy::transmute_ptr_to_ptr
)]
mod windows_ai_bindings;

// Generated from the pinned preview WinMD; regenerate with scripts/aion-bindings.
#[cfg(windows)]
#[rustfmt::skip]
#[allow(unsafe_code, non_snake_case, non_camel_case_types, non_upper_case_globals, dead_code, clippy::all, clippy::pedantic)]
mod aion_bindings;
#[cfg(windows)]
mod aion;
mod ondevice;
#[cfg(any(windows, test))]
mod package_buffer;
#[cfg(any(windows, test))]
mod stream;
pub use ondevice::{generate_ondevice_response, prepare_ondevice};

#[cfg(windows)]
#[allow(unsafe_code)]
mod laf;

// WinRT/COM work lives here; unsafe is scoped to this module and the
// package-identity probe below.
#[allow(unsafe_code)]
mod runtime;

pub use runtime::{
    OnDeviceAiStatus, OnDeviceModelEngine, PhiPromptFit, PhiSilicaAnalysisResponse,
    PhiSilicaStatus, ensure_phi_silica_ready, generate_response, is_phi_silica_available,
    measure_prompt_fit,
};

use wfdiag_native_ai_chat::{
    ChatProvider, ChatRequest, ChatTurn, FinishReason, flatten_chat_request,
};
use wfdiag_native_ai_provider::{BackendFuture, PhiStatusSnapshot, PhiStatusSource};

/// Chat adapter for an explicitly selected on-device backend.
///
/// Preparation runs before the shared inference deadline. Aion forwards preview
/// progress deltas; retail Phi emits its completed response. Both use flattened
/// retained prompts, keeping conversation state isolated by the shared engine.
/// The cancellation callback stops native work; dropping a preview future also
/// cancels it, including when a report's outer cancellation fires.
#[derive(Clone)]
pub struct PhiChatProvider {
    engine: OnDeviceModelEngine,
    is_cancelled: std::sync::Arc<dyn Fn() -> bool + Send + Sync>,
}

impl std::fmt::Debug for PhiChatProvider {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.debug_struct("PhiChatProvider").finish_non_exhaustive()
    }
}

impl Default for PhiChatProvider {
    fn default() -> Self {
        Self {
            engine: OnDeviceModelEngine::PhiSilica,
            is_cancelled: std::sync::Arc::new(|| false),
        }
    }
}

impl PhiChatProvider {
    #[must_use]
    pub fn for_engine(
        engine: OnDeviceModelEngine,
        is_cancelled: impl Fn() -> bool + Send + Sync + 'static,
    ) -> Self {
        Self {
            engine,
            is_cancelled: std::sync::Arc::new(is_cancelled),
        }
    }

    #[must_use]
    pub fn new(is_cancelled: impl Fn() -> bool + Send + Sync + 'static) -> Self {
        Self {
            engine: OnDeviceModelEngine::PhiSilica,
            is_cancelled: std::sync::Arc::new(is_cancelled),
        }
    }
}

impl ChatProvider for PhiChatProvider {
    fn preparation_label(&self) -> Option<&str> {
        (self.engine == OnDeviceModelEngine::AionInstruct)
            .then_some("Preparing Aion Instruct. First use can take several minutes.")
    }

    fn prepare(
        &self,
        cancel: tokio_util::sync::CancellationToken,
    ) -> BackendFuture<'_, Result<String, String>> {
        Box::pin(async move {
            let external = self.is_cancelled.clone();
            prepare_ondevice(self.engine, move || cancel.is_cancelled() || external()).await?;
            Ok(String::new())
        })
    }

    fn stream<'a>(
        &'a self,
        request: &'a ChatRequest,
        tx: tokio::sync::mpsc::Sender<String>,
    ) -> std::pin::Pin<Box<dyn std::future::Future<Output = Result<ChatTurn, String>> + Send + 'a>>
    {
        Box::pin(async move {
            let is_cancelled = self.is_cancelled.clone();
            let text = ondevice::generate_prepared(
                self.engine,
                &flatten_chat_request(request),
                move || is_cancelled(),
                Some(tx),
            )
            .await?;
            Ok(ChatTurn {
                text,
                tool_calls: Vec::new(),
                finished: FinishReason::Stop,
                actual_models: if self.engine == OnDeviceModelEngine::AionInstruct {
                    vec!["Aion Instruct Preview".into()]
                } else {
                    Vec::new()
                },
                provider_replay: None,
            })
        })
    }
}

/// Real package-identity/LAF-aware status source shared by Tauri and Reactor.
#[derive(Debug, Clone, Copy, Default)]
pub struct WindowsPhiStatusSource;

impl PhiStatusSource for WindowsPhiStatusSource {
    fn probe_aion(&self) -> BackendFuture<'_, PhiStatusSnapshot> {
        Box::pin(async {
            #[cfg(windows)]
            let result = tokio::task::spawn_blocking(aion::probe)
                .await
                .unwrap_or_else(|e| Err(format!("Aion probe failed: {e}")));
            #[cfg(not(windows))]
            let result: Result<(), String> = Err("Aion Instruct requires Windows".into());
            PhiStatusSnapshot {
                available: result.is_ok(), ready: result.is_ok(),
                message: Some(result.map_or_else(|error| error, |()|
                    "Aion Preview is installed. Model preparation on first use can take several minutes; QNN prerequisites must be installed.".into())),
                model_name: Some("Aion Instruct Preview".into()), is_aion: true,
            }
        })
    }

    fn probe(&self) -> BackendFuture<'_, PhiStatusSnapshot> {
        Box::pin(async {
            match probe_phi_silica_status().await {
                Ok(status) => PhiStatusSnapshot {
                    available: status.available,
                    ready: status.ready_state.as_deref() == Some("Ready"),
                    message: Some(status.message),
                    model_name: None, // Retail API exposes no actual model/version identity.
                    is_aion: status.engine == Some(OnDeviceModelEngine::AionInstruct),
                },
                Err(error) => PhiStatusSnapshot {
                    available: false,
                    ready: false,
                    message: Some(error),
                    model_name: None,
                    is_aion: false,
                },
            }
        })
    }
}

/// Run the blocking `WinRT` availability probe off the async runtime worker.
pub async fn probe_phi_silica_status() -> Result<PhiSilicaStatus, String> {
    tokio::task::spawn_blocking(is_phi_silica_available)
        .await
        .map_err(|error| format!("On-device AI availability check task panicked: {error}"))
}

/// Alias for `probe_phi_silica_status` to reflect dual on-device SLM support.
pub async fn probe_ondevice_ai_status() -> Result<OnDeviceAiStatus, String> {
    probe_phi_silica_status().await
}

/// True when the current process has registered package identity.
///
/// The runtime checks this before initializing `WinRT`, loading Windows App SDK
/// DLLs, or attempting LAF unlock. A loose executable therefore never reaches
/// the Windows AI activation path.
#[cfg(windows)]
#[must_use]
#[allow(unsafe_code)] // one Win32 call: package identity probe
pub fn has_package_identity() -> bool {
    windows_link::link!("kernel32.dll" "system" fn GetCurrentPackageFullName(package_full_name_length: *mut u32, package_full_name: *mut u16) -> u32);
    const ERROR_INSUFFICIENT_BUFFER: u32 = 122;

    let mut length = 0;
    let result = unsafe { GetCurrentPackageFullName(&raw mut length, std::ptr::null_mut()) };
    result == ERROR_INSUFFICIENT_BUFFER
}

#[cfg(not(windows))]
#[must_use]
pub const fn has_package_identity() -> bool {
    false
}

#[derive(Debug)]
enum PhiError {
    #[cfg(windows)]
    AiUnavailable { provider: String, reason: String },
    #[cfg(not(windows))]
    PlatformNotSupported { operation: String },
}

impl PhiError {
    #[cfg(windows)]
    fn ai_unavailable(provider: impl Into<String>, reason: impl Into<String>) -> Self {
        Self::AiUnavailable {
            provider: provider.into(),
            reason: reason.into(),
        }
    }
}

impl From<PhiError> for String {
    fn from(error: PhiError) -> Self {
        match error {
            #[cfg(windows)]
            PhiError::AiUnavailable { provider, reason } => {
                let label = match provider.as_str() {
                    "phi_silica" => "Phi Silica",
                    "aion_instruct" => "Aion Instruct",
                    "on_device" => "On-device AI",
                    other => other,
                };
                format!("{label} is unavailable: {reason}")
            }
            #[cfg(not(windows))]
            PhiError::PlatformNotSupported { operation } => {
                format!("{operation} is only available on Windows")
            }
        }
    }
}

#[cfg(windows)]
fn format_log_time(time: SystemTime) -> String {
    let seconds = time
        .duration_since(UNIX_EPOCH)
        .unwrap_or_default()
        .as_secs();
    format!(
        "{:02}:{:02}:{:02}",
        (seconds / 3600) % 24,
        (seconds % 3600) / 60,
        seconds % 60
    )
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn non_windows_identity_is_false() {
        #[cfg(not(windows))]
        assert!(!has_package_identity());
    }

    #[test]
    fn chat_adapter_keeps_history_and_current_question() {
        let request = ChatRequest {
            system: Some("Use only supplied evidence.".to_string()),
            messages: vec![
                wfdiag_native_ai_chat::ChatMessage::user("Is my disk healthy?"),
                wfdiag_native_ai_chat::ChatMessage::assistant("I need more evidence."),
                wfdiag_native_ai_chat::ChatMessage::user("Current free space is 8%."),
            ],
            tools: Vec::new(),
            max_tokens: None,
        };
        let prompt = flatten_chat_request(&request);
        assert!(prompt.starts_with("Use only supplied evidence."));
        assert!(prompt.contains("User: Is my disk healthy?"));
        assert!(prompt.contains("Assistant: I need more evidence."));
        assert!(prompt.contains("User: Current free space is 8%."));
        assert!(prompt.ends_with("Assistant:"));
    }

    #[cfg(not(windows))]
    #[test]
    fn provider_adapter_projects_the_platform_status() {
        let runtime = tokio::runtime::Builder::new_current_thread()
            .build()
            .expect("test runtime");
        let status = runtime.block_on(WindowsPhiStatusSource.probe());

        assert!(!status.available);
        assert!(!status.ready);
        assert_eq!(
            status.message.as_deref(),
            Some("Phi Silica is only available on Windows")
        );
    }

    #[cfg(windows)]
    #[test]
    fn phi_errors_render_as_readable_messages() {
        // The error string is the user-visible chat/analysis failure text;
        // it used to be a serialized JSON envelope (R4-F4-2).
        let rendered: String = PhiError::ai_unavailable("phi_silica", "not ready").into();
        assert_eq!(rendered, "Phi Silica is unavailable: not ready");
    }
}
