// Bindings generated by `windows-bindgen` 0.65.0

#![allow(
    non_snake_case,
    non_upper_case_globals,
    non_camel_case_types,
    dead_code,
    clippy::all
)]

pub mod Microsoft {
    pub mod Windows {
        pub mod AI {
            pub mod Generative {
                windows_core::imp::define_interface!(
                    IImageDescriptionGenerator,
                    IImageDescriptionGenerator_Vtbl,
                    0x201d9382_acbd_5b77_8d54_58c68c739e9c
                );
                impl windows_core::RuntimeType for IImageDescriptionGenerator {
                    const SIGNATURE: windows_core::imp::ConstBuffer =
                        windows_core::imp::ConstBuffer::for_interface::<Self>();
                }
                #[repr(C)]
                #[doc(hidden)]
                pub struct IImageDescriptionGenerator_Vtbl {
                    pub base__: windows_core::IInspectable_Vtbl,
                    DescribeAsync: usize,
                }
                windows_core::imp::define_interface!(
                    IImageDescriptionGenerator2,
                    IImageDescriptionGenerator2_Vtbl,
                    0x724ce13e_014e_5c20_873c_4d1cde8c8290
                );
                impl windows_core::RuntimeType for IImageDescriptionGenerator2 {
                    const SIGNATURE: windows_core::imp::ConstBuffer =
                        windows_core::imp::ConstBuffer::for_interface::<Self>();
                }
                #[repr(C)]
                #[doc(hidden)]
                pub struct IImageDescriptionGenerator2_Vtbl {
                    pub base__: windows_core::IInspectable_Vtbl,
                    DescribeAsync: usize,
                }
                windows_core::imp::define_interface!(
                    IImageDescriptionGenerator3,
                    IImageDescriptionGenerator3_Vtbl,
                    0xd4a3ad04_728e_5fd9_908e_db32dc0ef41b
                );
                impl windows_core::RuntimeType for IImageDescriptionGenerator3 {
                    const SIGNATURE: windows_core::imp::ConstBuffer =
                        windows_core::imp::ConstBuffer::for_interface::<Self>();
                }
                #[repr(C)]
                #[doc(hidden)]
                pub struct IImageDescriptionGenerator3_Vtbl {
                    pub base__: windows_core::IInspectable_Vtbl,
                    DescribeAsync: usize,
                }
                windows_core::imp::define_interface!(
                    IImageDescriptionGeneratorStatics,
                    IImageDescriptionGeneratorStatics_Vtbl,
                    0xffa3bf30_f7b1_5ef5_a730_fe3759be09b5
                );
                impl windows_core::RuntimeType for IImageDescriptionGeneratorStatics {
                    const SIGNATURE: windows_core::imp::ConstBuffer =
                        windows_core::imp::ConstBuffer::for_interface::<Self>();
                }
                #[repr(C)]
                #[doc(hidden)]
                pub struct IImageDescriptionGeneratorStatics_Vtbl {
                    pub base__: windows_core::IInspectable_Vtbl,
                    pub IsAvailable: unsafe extern "system" fn(
                        *mut core::ffi::c_void,
                        *mut bool,
                    )
                        -> windows_core::HRESULT,
                    MakeAvailableAsync: usize,
                    pub CreateAsync: unsafe extern "system" fn(
                        *mut core::ffi::c_void,
                        *mut *mut core::ffi::c_void,
                    )
                        -> windows_core::HRESULT,
                }
                windows_core::imp::define_interface!(
                    ILanguageModel,
                    ILanguageModel_Vtbl,
                    0x38b8a444_8ba1_5409_a916_dc1f7851bea3
                );
                impl windows_core::RuntimeType for ILanguageModel {
                    const SIGNATURE: windows_core::imp::ConstBuffer =
                        windows_core::imp::ConstBuffer::for_interface::<Self>();
                }
                #[repr(C)]
                #[doc(hidden)]
                pub struct ILanguageModel_Vtbl {
                    pub base__: windows_core::IInspectable_Vtbl,
                    pub GenerateResponseAsync: unsafe extern "system" fn(
                        *mut core::ffi::c_void,
                        *mut core::ffi::c_void,
                        *mut *mut core::ffi::c_void,
                    )
                        -> windows_core::HRESULT,
                    pub GenerateResponseWithProgressAsync:
                        unsafe extern "system" fn(
                            *mut core::ffi::c_void,
                            *mut core::ffi::c_void,
                            *mut *mut core::ffi::c_void,
                        ) -> windows_core::HRESULT,
                }
                windows_core::imp::define_interface!(
                    ILanguageModel2,
                    ILanguageModel2_Vtbl,
                    0xcbb284c3_d42e_5cf5_ada4_6bec6cec8784
                );
                impl windows_core::RuntimeType for ILanguageModel2 {
                    const SIGNATURE: windows_core::imp::ConstBuffer =
                        windows_core::imp::ConstBuffer::for_interface::<Self>();
                }
                #[repr(C)]
                #[doc(hidden)]
                pub struct ILanguageModel2_Vtbl {
                    pub base__: windows_core::IInspectable_Vtbl,
                    GenerateResponseFromEmbeddingsWithProgressAsync: usize,
                    GenerateEmbeddingVector: usize,
                    GenerateEmbeddingVectorAsync: usize,
                    pub IsPromptLargerThanContext:
                        unsafe extern "system" fn(
                            *mut core::ffi::c_void,
                            *mut core::ffi::c_void,
                            *mut bool,
                        ) -> windows_core::HRESULT,
                }
                windows_core::imp::define_interface!(
                    ILanguageModel3,
                    ILanguageModel3_Vtbl,
                    0xa05361ee_3ac3_5459_9c0c_e08a35a01032
                );
                impl windows_core::RuntimeType for ILanguageModel3 {
                    const SIGNATURE: windows_core::imp::ConstBuffer =
                        windows_core::imp::ConstBuffer::for_interface::<Self>();
                }
                #[repr(C)]
                #[doc(hidden)]
                pub struct ILanguageModel3_Vtbl {
                    pub base__: windows_core::IInspectable_Vtbl,
                    pub GenerateResponseAsync: unsafe extern "system" fn(
                        *mut core::ffi::c_void,
                        *mut core::ffi::c_void,
                        *mut core::ffi::c_void,
                        *mut *mut core::ffi::c_void,
                    )
                        -> windows_core::HRESULT,
                    GenerateResponseFromEmbeddingsWithProgressAsync: usize,
                }
                windows_core::imp::define_interface!(
                    ILanguageModel4,
                    ILanguageModel4_Vtbl,
                    0x0ccac517_e9f4_5f5b_a404_f14e560fcac1
                );
                impl windows_core::RuntimeType for ILanguageModel4 {
                    const SIGNATURE: windows_core::imp::ConstBuffer =
                        windows_core::imp::ConstBuffer::for_interface::<Self>();
                }
                #[repr(C)]
                #[doc(hidden)]
                pub struct ILanguageModel4_Vtbl {
                    pub base__: windows_core::IInspectable_Vtbl,
                    pub GenerateResponseWithProgressAsync:
                        unsafe extern "system" fn(
                            *mut core::ffi::c_void,
                            *mut core::ffi::c_void,
                            *mut core::ffi::c_void,
                            *mut *mut core::ffi::c_void,
                        ) -> windows_core::HRESULT,
                    pub GenerateTokens: unsafe extern "system" fn(
                        *mut core::ffi::c_void,
                        *mut core::ffi::c_void,
                        *mut *mut core::ffi::c_void,
                    )
                        -> windows_core::HRESULT,
                    pub GenerateTokensAsync: unsafe extern "system" fn(
                        *mut core::ffi::c_void,
                        *mut core::ffi::c_void,
                        *mut *mut core::ffi::c_void,
                    )
                        -> windows_core::HRESULT,
                    pub GenerateResponseFromTokensWithProgressAsync:
                        unsafe extern "system" fn(
                            *mut core::ffi::c_void,
                            *mut core::ffi::c_void,
                            *mut core::ffi::c_void,
                            *mut *mut core::ffi::c_void,
                        ) -> windows_core::HRESULT,
                }
                windows_core::imp::define_interface!(
                    ILanguageModel5,
                    ILanguageModel5_Vtbl,
                    0xd9700fc8_f41f_5c98_b368_0962447ef2ca
                );
                impl windows_core::RuntimeType for ILanguageModel5 {
                    const SIGNATURE: windows_core::imp::ConstBuffer =
                        windows_core::imp::ConstBuffer::for_interface::<Self>();
                }
                #[repr(C)]
                #[doc(hidden)]
                pub struct ILanguageModel5_Vtbl {
                    pub base__: windows_core::IInspectable_Vtbl,
                    GenerateResponseAsync: usize,
                    GenerateResponseWithProgressAsync: usize,
                    GenerateResponseFromEmbeddingsWithProgressAsync: usize,
                    GenerateResponseFromTokensWithProgressAsync: usize,
                    GenerateResponseAsync2: usize,
                    GenerateResponseWithProgressAsync2: usize,
                    GenerateResponseFromEmbeddingsWithProgressAsync2: usize,
                    GenerateResponseFromTokensWithProgressAsync2: usize,
                    GenerateEmbeddingVector: usize,
                    GenerateEmbeddingVectorAsync: usize,
                    GenerateTokens: usize,
                    GenerateTokensAsync: usize,
                    pub CreateContext: unsafe extern "system" fn(
                        *mut core::ffi::c_void,
                        *mut *mut core::ffi::c_void,
                    )
                        -> windows_core::HRESULT,
                    CreateContext2: usize,
                    pub IsPromptLargerThanContext:
                        unsafe extern "system" fn(
                            *mut core::ffi::c_void,
                            *mut core::ffi::c_void,
                            *mut core::ffi::c_void,
                            *mut bool,
                        ) -> windows_core::HRESULT,
                }
                windows_core::imp::define_interface!(
                    ILanguageModelContext,
                    ILanguageModelContext_Vtbl,
                    0xc8948656_8131_5f7a_81c8_28279bba0a86
                );
                impl windows_core::RuntimeType for ILanguageModelContext {
                    const SIGNATURE: windows_core::imp::ConstBuffer =
                        windows_core::imp::ConstBuffer::for_interface::<Self>();
                }
                #[repr(C)]
                #[doc(hidden)]
                pub struct ILanguageModelContext_Vtbl {
                    pub base__: windows_core::IInspectable_Vtbl,
                }
                windows_core::imp::define_interface!(
                    ILanguageModelOptions,
                    ILanguageModelOptions_Vtbl,
                    0x32ceca03_b0a2_56d2_92d5_f65270ab7637
                );
                impl windows_core::RuntimeType for ILanguageModelOptions {
                    const SIGNATURE: windows_core::imp::ConstBuffer =
                        windows_core::imp::ConstBuffer::for_interface::<Self>();
                }
                #[repr(C)]
                #[doc(hidden)]
                pub struct ILanguageModelOptions_Vtbl {
                    pub base__: windows_core::IInspectable_Vtbl,
                    pub Skill: unsafe extern "system" fn(
                        *mut core::ffi::c_void,
                        *mut LanguageModelSkill,
                    )
                        -> windows_core::HRESULT,
                    pub SetSkill: unsafe extern "system" fn(
                        *mut core::ffi::c_void,
                        LanguageModelSkill,
                    )
                        -> windows_core::HRESULT,
                    pub Temp: unsafe extern "system" fn(
                        *mut core::ffi::c_void,
                        *mut f32,
                    )
                        -> windows_core::HRESULT,
                    pub SetTemp: unsafe extern "system" fn(
                        *mut core::ffi::c_void,
                        f32,
                    )
                        -> windows_core::HRESULT,
                    pub Top_p: unsafe extern "system" fn(
                        *mut core::ffi::c_void,
                        *mut f32,
                    )
                        -> windows_core::HRESULT,
                    pub SetTop_p: unsafe extern "system" fn(
                        *mut core::ffi::c_void,
                        f32,
                    )
                        -> windows_core::HRESULT,
                    pub Top_k: unsafe extern "system" fn(
                        *mut core::ffi::c_void,
                        *mut u32,
                    )
                        -> windows_core::HRESULT,
                    pub SetTop_k: unsafe extern "system" fn(
                        *mut core::ffi::c_void,
                        u32,
                    )
                        -> windows_core::HRESULT,
                }
                windows_core::imp::define_interface!(
                    ILanguageModelOptionsFactory,
                    ILanguageModelOptionsFactory_Vtbl,
                    0x5e48af80_f5bb_5223_b251_fbc871beb848
                );
                impl windows_core::RuntimeType for ILanguageModelOptionsFactory {
                    const SIGNATURE: windows_core::imp::ConstBuffer =
                        windows_core::imp::ConstBuffer::for_interface::<Self>();
                }
                #[repr(C)]
                #[doc(hidden)]
                pub struct ILanguageModelOptionsFactory_Vtbl {
                    pub base__: windows_core::IInspectable_Vtbl,
                    pub CreateInstance: unsafe extern "system" fn(
                        *mut core::ffi::c_void,
                        LanguageModelSkill,
                        f32,
                        f32,
                        u32,
                        *mut *mut core::ffi::c_void,
                    )
                        -> windows_core::HRESULT,
                }
                windows_core::imp::define_interface!(
                    ILanguageModelResponse,
                    ILanguageModelResponse_Vtbl,
                    0x0cc262b4_d0f1_526e_904e_f9db35c90d33
                );
                impl windows_core::RuntimeType for ILanguageModelResponse {
                    const SIGNATURE: windows_core::imp::ConstBuffer =
                        windows_core::imp::ConstBuffer::for_interface::<Self>();
                }
                #[repr(C)]
                #[doc(hidden)]
                pub struct ILanguageModelResponse_Vtbl {
                    pub base__: windows_core::IInspectable_Vtbl,
                    pub Response: unsafe extern "system" fn(
                        *mut core::ffi::c_void,
                        *mut *mut core::ffi::c_void,
                    )
                        -> windows_core::HRESULT,
                    pub Status: unsafe extern "system" fn(
                        *mut core::ffi::c_void,
                        *mut LanguageModelResponseStatus,
                    )
                        -> windows_core::HRESULT,
                }
                windows_core::imp::define_interface!(
                    ILanguageModelResponseFactory,
                    ILanguageModelResponseFactory_Vtbl,
                    0xe271f832_9a93_5485_a76a_ec91339beab2
                );
                impl windows_core::RuntimeType for ILanguageModelResponseFactory {
                    const SIGNATURE: windows_core::imp::ConstBuffer =
                        windows_core::imp::ConstBuffer::for_interface::<Self>();
                }
                #[repr(C)]
                #[doc(hidden)]
                pub struct ILanguageModelResponseFactory_Vtbl {
                    pub base__: windows_core::IInspectable_Vtbl,
                    pub CreateInstance: unsafe extern "system" fn(
                        *mut core::ffi::c_void,
                        *mut core::ffi::c_void,
                        LanguageModelResponseStatus,
                        *mut *mut core::ffi::c_void,
                    )
                        -> windows_core::HRESULT,
                }
                windows_core::imp::define_interface!(
                    ILanguageModelStatics,
                    ILanguageModelStatics_Vtbl,
                    0x122c5800_8823_50f6_9d94_77e4c19d3721
                );
                impl windows_core::RuntimeType for ILanguageModelStatics {
                    const SIGNATURE: windows_core::imp::ConstBuffer =
                        windows_core::imp::ConstBuffer::for_interface::<Self>();
                }
                #[repr(C)]
                #[doc(hidden)]
                pub struct ILanguageModelStatics_Vtbl {
                    pub base__: windows_core::IInspectable_Vtbl,
                    pub IsAvailable: unsafe extern "system" fn(
                        *mut core::ffi::c_void,
                        *mut bool,
                    )
                        -> windows_core::HRESULT,
                    MakeAvailableAsync: usize,
                    pub CreateAsync: unsafe extern "system" fn(
                        *mut core::ffi::c_void,
                        *mut *mut core::ffi::c_void,
                    )
                        -> windows_core::HRESULT,
                }
                #[repr(transparent)]
                #[derive(Clone, Debug, Eq, PartialEq)]
                pub struct ImageDescriptionGenerator(windows_core::IUnknown);
                windows_core::imp::interface_hierarchy!(
                    ImageDescriptionGenerator,
                    windows_core::IUnknown,
                    windows_core::IInspectable
                );
                windows_core::imp::required_hierarchy!(
                    ImageDescriptionGenerator,
                    super::super::super::super::Windows::Foundation::IClosable
                );
                impl ImageDescriptionGenerator {
                    pub fn Close(&self) -> windows_core::Result<()> {
                        let this = &windows_core::Interface::cast::<
                            super::super::super::super::Windows::Foundation::IClosable,
                        >(self)?;
                        unsafe {
                            (windows_core::Interface::vtable(this).Close)(
                                windows_core::Interface::as_raw(this),
                            )
                            .ok()
                        }
                    }
                    pub fn IsAvailable() -> windows_core::Result<bool> {
                        Self::IImageDescriptionGeneratorStatics(|this| unsafe {
                            let mut result__ = core::mem::zeroed();
                            (windows_core::Interface::vtable(this).IsAvailable)(
                                windows_core::Interface::as_raw(this),
                                &mut result__,
                            )
                            .map(|| result__)
                        })
                    }
                    pub fn CreateAsync() -> windows_core::Result<
                        windows_future::IAsyncOperation<ImageDescriptionGenerator>,
                    > {
                        Self::IImageDescriptionGeneratorStatics(|this| unsafe {
                            let mut result__ = core::mem::zeroed();
                            (windows_core::Interface::vtable(this).CreateAsync)(
                                windows_core::Interface::as_raw(this),
                                &mut result__,
                            )
                            .and_then(|| windows_core::Type::from_abi(result__))
                        })
                    }
                    fn IImageDescriptionGeneratorStatics<
                        R,
                        F: FnOnce(&IImageDescriptionGeneratorStatics) -> windows_core::Result<R>,
                    >(
                        callback: F,
                    ) -> windows_core::Result<R> {
                        static SHARED: windows_core::imp::FactoryCache<
                            ImageDescriptionGenerator,
                            IImageDescriptionGeneratorStatics,
                        > = windows_core::imp::FactoryCache::new();
                        SHARED.call(callback)
                    }
                }
                impl windows_core::RuntimeType for ImageDescriptionGenerator {
                    const SIGNATURE: windows_core::imp::ConstBuffer =
                        windows_core::imp::ConstBuffer::for_class::<Self, IImageDescriptionGenerator>(
                        );
                }
                unsafe impl windows_core::Interface for ImageDescriptionGenerator {
                    type Vtable = <IImageDescriptionGenerator as windows_core::Interface>::Vtable;
                    const IID: windows_core::GUID =
                        <IImageDescriptionGenerator as windows_core::Interface>::IID;
                }
                impl windows_core::RuntimeName for ImageDescriptionGenerator {
                    const NAME: &'static str =
                        "Microsoft.Windows.AI.Generative.ImageDescriptionGenerator";
                }
                unsafe impl Send for ImageDescriptionGenerator {}
                unsafe impl Sync for ImageDescriptionGenerator {}
                #[repr(transparent)]
                #[derive(Clone, Copy, Debug, Default, Eq, PartialEq)]
                pub struct ImageDescriptionScenario(pub i32);
                impl ImageDescriptionScenario {
                    pub const Accessibility: Self = Self(1i32);
                    pub const Caption: Self = Self(2i32);
                    pub const DetailedNarration: Self = Self(3i32);
                    pub const OfficeCharts: Self = Self(4i32);
                }
                impl windows_core::TypeKind for ImageDescriptionScenario {
                    type TypeKind = windows_core::CopyType;
                }
                impl windows_core::RuntimeType for ImageDescriptionScenario {
                    const SIGNATURE: windows_core::imp::ConstBuffer =
                        windows_core::imp::ConstBuffer::from_slice(
                            b"enum(Microsoft.Windows.AI.Generative.ImageDescriptionScenario;i4)",
                        );
                }
                #[repr(transparent)]
                #[derive(Clone, Debug, Eq, PartialEq)]
                pub struct LanguageModel(windows_core::IUnknown);
                windows_core::imp::interface_hierarchy!(
                    LanguageModel,
                    windows_core::IUnknown,
                    windows_core::IInspectable
                );
                windows_core::imp::required_hierarchy!(
                    LanguageModel,
                    super::super::super::super::Windows::Foundation::IClosable
                );
                impl LanguageModel {
                    pub fn Close(&self) -> windows_core::Result<()> {
                        let this = &windows_core::Interface::cast::<
                            super::super::super::super::Windows::Foundation::IClosable,
                        >(self)?;
                        unsafe {
                            (windows_core::Interface::vtable(this).Close)(
                                windows_core::Interface::as_raw(this),
                            )
                            .ok()
                        }
                    }
                    pub fn GenerateResponseAsync(
                        &self,
                        prompt: &windows_core::HSTRING,
                    ) -> windows_core::Result<windows_future::IAsyncOperation<LanguageModelResponse>>
                    {
                        let this = self;
                        unsafe {
                            let mut result__ = core::mem::zeroed();
                            (windows_core::Interface::vtable(this).GenerateResponseAsync)(
                                windows_core::Interface::as_raw(this),
                                core::mem::transmute_copy(prompt),
                                &mut result__,
                            )
                            .and_then(|| windows_core::Type::from_abi(result__))
                        }
                    }
                    pub fn GenerateResponseWithProgressAsync(
                        &self,
                        prompt: &windows_core::HSTRING,
                    ) -> windows_core::Result<
                        windows_future::IAsyncOperationWithProgress<
                            LanguageModelResponse,
                            windows_core::HSTRING,
                        >,
                    > {
                        let this = self;
                        unsafe {
                            let mut result__ = core::mem::zeroed();
                            (windows_core::Interface::vtable(this)
                                .GenerateResponseWithProgressAsync)(
                                windows_core::Interface::as_raw(this),
                                core::mem::transmute_copy(prompt),
                                &mut result__,
                            )
                            .and_then(|| windows_core::Type::from_abi(result__))
                        }
                    }
                    pub fn IsPromptLargerThanContext(
                        &self,
                        prompt: &windows_core::HSTRING,
                    ) -> windows_core::Result<bool> {
                        let this = &windows_core::Interface::cast::<ILanguageModel2>(self)?;
                        unsafe {
                            let mut result__ = core::mem::zeroed();
                            (windows_core::Interface::vtable(this).IsPromptLargerThanContext)(
                                windows_core::Interface::as_raw(this),
                                core::mem::transmute_copy(prompt),
                                &mut result__,
                            )
                            .map(|| result__)
                        }
                    }
                    pub fn GenerateResponseAsync2<P0>(
                        &self,
                        options: P0,
                        prompt: &windows_core::HSTRING,
                    ) -> windows_core::Result<windows_future::IAsyncOperation<LanguageModelResponse>>
                    where
                        P0: windows_core::Param<LanguageModelOptions>,
                    {
                        let this = &windows_core::Interface::cast::<ILanguageModel3>(self)?;
                        unsafe {
                            let mut result__ = core::mem::zeroed();
                            (windows_core::Interface::vtable(this).GenerateResponseAsync)(
                                windows_core::Interface::as_raw(this),
                                options.param().abi(),
                                core::mem::transmute_copy(prompt),
                                &mut result__,
                            )
                            .and_then(|| windows_core::Type::from_abi(result__))
                        }
                    }
                    pub fn GenerateResponseWithProgressAsync2<P0>(
                        &self,
                        options: P0,
                        prompt: &windows_core::HSTRING,
                    ) -> windows_core::Result<
                        windows_future::IAsyncOperationWithProgress<
                            LanguageModelResponse,
                            windows_core::HSTRING,
                        >,
                    >
                    where
                        P0: windows_core::Param<LanguageModelOptions>,
                    {
                        let this = &windows_core::Interface::cast::<ILanguageModel4>(self)?;
                        unsafe {
                            let mut result__ = core::mem::zeroed();
                            (windows_core::Interface::vtable(this)
                                .GenerateResponseWithProgressAsync)(
                                windows_core::Interface::as_raw(this),
                                options.param().abi(),
                                core::mem::transmute_copy(prompt),
                                &mut result__,
                            )
                            .and_then(|| windows_core::Type::from_abi(result__))
                        }
                    }
                    pub fn GenerateTokens(
                        &self,
                        text: &windows_core::HSTRING,
                    ) -> windows_core::Result<windows_collections::IVectorView<i64>>
                    {
                        let this = &windows_core::Interface::cast::<ILanguageModel4>(self)?;
                        unsafe {
                            let mut result__ = core::mem::zeroed();
                            (windows_core::Interface::vtable(this).GenerateTokens)(
                                windows_core::Interface::as_raw(this),
                                core::mem::transmute_copy(text),
                                &mut result__,
                            )
                            .and_then(|| windows_core::Type::from_abi(result__))
                        }
                    }
                    pub fn GenerateTokensAsync(
                        &self,
                        text: &windows_core::HSTRING,
                    ) -> windows_core::Result<
                        windows_future::IAsyncOperation<windows_collections::IVectorView<i64>>,
                    > {
                        let this = &windows_core::Interface::cast::<ILanguageModel4>(self)?;
                        unsafe {
                            let mut result__ = core::mem::zeroed();
                            (windows_core::Interface::vtable(this).GenerateTokensAsync)(
                                windows_core::Interface::as_raw(this),
                                core::mem::transmute_copy(text),
                                &mut result__,
                            )
                            .and_then(|| windows_core::Type::from_abi(result__))
                        }
                    }
                    pub fn GenerateResponseFromTokensWithProgressAsync<P0, P1>(
                        &self,
                        options: P0,
                        prompttokens: P1,
                    ) -> windows_core::Result<
                        windows_future::IAsyncOperationWithProgress<
                            LanguageModelResponse,
                            windows_core::HSTRING,
                        >,
                    >
                    where
                        P0: windows_core::Param<LanguageModelOptions>,
                        P1: windows_core::Param<windows_collections::IVectorView<i64>>,
                    {
                        let this = &windows_core::Interface::cast::<ILanguageModel4>(self)?;
                        unsafe {
                            let mut result__ = core::mem::zeroed();
                            (windows_core::Interface::vtable(this)
                                .GenerateResponseFromTokensWithProgressAsync)(
                                windows_core::Interface::as_raw(this),
                                options.param().abi(),
                                prompttokens.param().abi(),
                                &mut result__,
                            )
                            .and_then(|| windows_core::Type::from_abi(result__))
                        }
                    }
                    pub fn CreateContext(&self) -> windows_core::Result<LanguageModelContext> {
                        let this = &windows_core::Interface::cast::<ILanguageModel5>(self)?;
                        unsafe {
                            let mut result__ = core::mem::zeroed();
                            (windows_core::Interface::vtable(this).CreateContext)(
                                windows_core::Interface::as_raw(this),
                                &mut result__,
                            )
                            .and_then(|| windows_core::Type::from_abi(result__))
                        }
                    }
                    pub fn IsPromptLargerThanContext2<P0>(
                        &self,
                        context: P0,
                        prompt: &windows_core::HSTRING,
                    ) -> windows_core::Result<bool>
                    where
                        P0: windows_core::Param<LanguageModelContext>,
                    {
                        let this = &windows_core::Interface::cast::<ILanguageModel5>(self)?;
                        unsafe {
                            let mut result__ = core::mem::zeroed();
                            (windows_core::Interface::vtable(this).IsPromptLargerThanContext)(
                                windows_core::Interface::as_raw(this),
                                context.param().abi(),
                                core::mem::transmute_copy(prompt),
                                &mut result__,
                            )
                            .map(|| result__)
                        }
                    }
                    pub fn IsAvailable() -> windows_core::Result<bool> {
                        Self::ILanguageModelStatics(|this| unsafe {
                            let mut result__ = core::mem::zeroed();
                            (windows_core::Interface::vtable(this).IsAvailable)(
                                windows_core::Interface::as_raw(this),
                                &mut result__,
                            )
                            .map(|| result__)
                        })
                    }
                    pub fn CreateAsync(
                    ) -> windows_core::Result<windows_future::IAsyncOperation<LanguageModel>>
                    {
                        Self::ILanguageModelStatics(|this| unsafe {
                            let mut result__ = core::mem::zeroed();
                            (windows_core::Interface::vtable(this).CreateAsync)(
                                windows_core::Interface::as_raw(this),
                                &mut result__,
                            )
                            .and_then(|| windows_core::Type::from_abi(result__))
                        })
                    }
                    fn ILanguageModelStatics<
                        R,
                        F: FnOnce(&ILanguageModelStatics) -> windows_core::Result<R>,
                    >(
                        callback: F,
                    ) -> windows_core::Result<R> {
                        static SHARED: windows_core::imp::FactoryCache<
                            LanguageModel,
                            ILanguageModelStatics,
                        > = windows_core::imp::FactoryCache::new();
                        SHARED.call(callback)
                    }
                }
                impl windows_core::RuntimeType for LanguageModel {
                    const SIGNATURE: windows_core::imp::ConstBuffer =
                        windows_core::imp::ConstBuffer::for_class::<Self, ILanguageModel>();
                }
                unsafe impl windows_core::Interface for LanguageModel {
                    type Vtable = <ILanguageModel as windows_core::Interface>::Vtable;
                    const IID: windows_core::GUID =
                        <ILanguageModel as windows_core::Interface>::IID;
                }
                impl windows_core::RuntimeName for LanguageModel {
                    const NAME: &'static str = "Microsoft.Windows.AI.Generative.LanguageModel";
                }
                unsafe impl Send for LanguageModel {}
                unsafe impl Sync for LanguageModel {}
                #[repr(transparent)]
                #[derive(Clone, Debug, Eq, PartialEq)]
                pub struct LanguageModelContext(windows_core::IUnknown);
                windows_core::imp::interface_hierarchy!(
                    LanguageModelContext,
                    windows_core::IUnknown,
                    windows_core::IInspectable
                );
                impl LanguageModelContext {}
                impl windows_core::RuntimeType for LanguageModelContext {
                    const SIGNATURE: windows_core::imp::ConstBuffer =
                        windows_core::imp::ConstBuffer::for_class::<Self, ILanguageModelContext>();
                }
                unsafe impl windows_core::Interface for LanguageModelContext {
                    type Vtable = <ILanguageModelContext as windows_core::Interface>::Vtable;
                    const IID: windows_core::GUID =
                        <ILanguageModelContext as windows_core::Interface>::IID;
                }
                impl windows_core::RuntimeName for LanguageModelContext {
                    const NAME: &'static str =
                        "Microsoft.Windows.AI.Generative.LanguageModelContext";
                }
                unsafe impl Send for LanguageModelContext {}
                unsafe impl Sync for LanguageModelContext {}
                #[repr(transparent)]
                #[derive(Clone, Debug, Eq, PartialEq)]
                pub struct LanguageModelOptions(windows_core::IUnknown);
                windows_core::imp::interface_hierarchy!(
                    LanguageModelOptions,
                    windows_core::IUnknown,
                    windows_core::IInspectable
                );
                impl LanguageModelOptions {
                    pub fn new() -> windows_core::Result<Self> {
                        Self::IActivationFactory(|f| f.ActivateInstance::<Self>())
                    }
                    fn IActivationFactory<
                        R,
                        F: FnOnce(&windows_core::imp::IGenericFactory) -> windows_core::Result<R>,
                    >(
                        callback: F,
                    ) -> windows_core::Result<R> {
                        static SHARED: windows_core::imp::FactoryCache<
                            LanguageModelOptions,
                            windows_core::imp::IGenericFactory,
                        > = windows_core::imp::FactoryCache::new();
                        SHARED.call(callback)
                    }
                    pub fn Skill(&self) -> windows_core::Result<LanguageModelSkill> {
                        let this = self;
                        unsafe {
                            let mut result__ = core::mem::zeroed();
                            (windows_core::Interface::vtable(this).Skill)(
                                windows_core::Interface::as_raw(this),
                                &mut result__,
                            )
                            .map(|| result__)
                        }
                    }
                    pub fn SetSkill(&self, value: LanguageModelSkill) -> windows_core::Result<()> {
                        let this = self;
                        unsafe {
                            (windows_core::Interface::vtable(this).SetSkill)(
                                windows_core::Interface::as_raw(this),
                                value,
                            )
                            .ok()
                        }
                    }
                    pub fn Temp(&self) -> windows_core::Result<f32> {
                        let this = self;
                        unsafe {
                            let mut result__ = core::mem::zeroed();
                            (windows_core::Interface::vtable(this).Temp)(
                                windows_core::Interface::as_raw(this),
                                &mut result__,
                            )
                            .map(|| result__)
                        }
                    }
                    pub fn SetTemp(&self, value: f32) -> windows_core::Result<()> {
                        let this = self;
                        unsafe {
                            (windows_core::Interface::vtable(this).SetTemp)(
                                windows_core::Interface::as_raw(this),
                                value,
                            )
                            .ok()
                        }
                    }
                    pub fn Top_p(&self) -> windows_core::Result<f32> {
                        let this = self;
                        unsafe {
                            let mut result__ = core::mem::zeroed();
                            (windows_core::Interface::vtable(this).Top_p)(
                                windows_core::Interface::as_raw(this),
                                &mut result__,
                            )
                            .map(|| result__)
                        }
                    }
                    pub fn SetTop_p(&self, value: f32) -> windows_core::Result<()> {
                        let this = self;
                        unsafe {
                            (windows_core::Interface::vtable(this).SetTop_p)(
                                windows_core::Interface::as_raw(this),
                                value,
                            )
                            .ok()
                        }
                    }
                    pub fn Top_k(&self) -> windows_core::Result<u32> {
                        let this = self;
                        unsafe {
                            let mut result__ = core::mem::zeroed();
                            (windows_core::Interface::vtable(this).Top_k)(
                                windows_core::Interface::as_raw(this),
                                &mut result__,
                            )
                            .map(|| result__)
                        }
                    }
                    pub fn SetTop_k(&self, value: u32) -> windows_core::Result<()> {
                        let this = self;
                        unsafe {
                            (windows_core::Interface::vtable(this).SetTop_k)(
                                windows_core::Interface::as_raw(this),
                                value,
                            )
                            .ok()
                        }
                    }
                    pub fn CreateInstance(
                        skill: LanguageModelSkill,
                        temp: f32,
                        top_p: f32,
                        top_k: u32,
                    ) -> windows_core::Result<LanguageModelOptions> {
                        Self::ILanguageModelOptionsFactory(|this| unsafe {
                            let mut result__ = core::mem::zeroed();
                            (windows_core::Interface::vtable(this).CreateInstance)(
                                windows_core::Interface::as_raw(this),
                                skill,
                                temp,
                                top_p,
                                top_k,
                                &mut result__,
                            )
                            .and_then(|| windows_core::Type::from_abi(result__))
                        })
                    }
                    fn ILanguageModelOptionsFactory<
                        R,
                        F: FnOnce(&ILanguageModelOptionsFactory) -> windows_core::Result<R>,
                    >(
                        callback: F,
                    ) -> windows_core::Result<R> {
                        static SHARED: windows_core::imp::FactoryCache<
                            LanguageModelOptions,
                            ILanguageModelOptionsFactory,
                        > = windows_core::imp::FactoryCache::new();
                        SHARED.call(callback)
                    }
                }
                impl windows_core::RuntimeType for LanguageModelOptions {
                    const SIGNATURE: windows_core::imp::ConstBuffer =
                        windows_core::imp::ConstBuffer::for_class::<Self, ILanguageModelOptions>();
                }
                unsafe impl windows_core::Interface for LanguageModelOptions {
                    type Vtable = <ILanguageModelOptions as windows_core::Interface>::Vtable;
                    const IID: windows_core::GUID =
                        <ILanguageModelOptions as windows_core::Interface>::IID;
                }
                impl windows_core::RuntimeName for LanguageModelOptions {
                    const NAME: &'static str =
                        "Microsoft.Windows.AI.Generative.LanguageModelOptions";
                }
                unsafe impl Send for LanguageModelOptions {}
                unsafe impl Sync for LanguageModelOptions {}
                #[repr(transparent)]
                #[derive(Clone, Debug, Eq, PartialEq)]
                pub struct LanguageModelResponse(windows_core::IUnknown);
                windows_core::imp::interface_hierarchy!(
                    LanguageModelResponse,
                    windows_core::IUnknown,
                    windows_core::IInspectable
                );
                impl LanguageModelResponse {
                    pub fn Response(&self) -> windows_core::Result<windows_core::HSTRING> {
                        let this = self;
                        unsafe {
                            let mut result__ = core::mem::zeroed();
                            (windows_core::Interface::vtable(this).Response)(
                                windows_core::Interface::as_raw(this),
                                &mut result__,
                            )
                            .map(|| core::mem::transmute(result__))
                        }
                    }
                    pub fn Status(&self) -> windows_core::Result<LanguageModelResponseStatus> {
                        let this = self;
                        unsafe {
                            let mut result__ = core::mem::zeroed();
                            (windows_core::Interface::vtable(this).Status)(
                                windows_core::Interface::as_raw(this),
                                &mut result__,
                            )
                            .map(|| result__)
                        }
                    }
                    pub fn CreateInstance(
                        response: &windows_core::HSTRING,
                        status: LanguageModelResponseStatus,
                    ) -> windows_core::Result<LanguageModelResponse> {
                        Self::ILanguageModelResponseFactory(|this| unsafe {
                            let mut result__ = core::mem::zeroed();
                            (windows_core::Interface::vtable(this).CreateInstance)(
                                windows_core::Interface::as_raw(this),
                                core::mem::transmute_copy(response),
                                status,
                                &mut result__,
                            )
                            .and_then(|| windows_core::Type::from_abi(result__))
                        })
                    }
                    fn ILanguageModelResponseFactory<
                        R,
                        F: FnOnce(&ILanguageModelResponseFactory) -> windows_core::Result<R>,
                    >(
                        callback: F,
                    ) -> windows_core::Result<R> {
                        static SHARED: windows_core::imp::FactoryCache<
                            LanguageModelResponse,
                            ILanguageModelResponseFactory,
                        > = windows_core::imp::FactoryCache::new();
                        SHARED.call(callback)
                    }
                }
                impl windows_core::RuntimeType for LanguageModelResponse {
                    const SIGNATURE: windows_core::imp::ConstBuffer =
                        windows_core::imp::ConstBuffer::for_class::<Self, ILanguageModelResponse>();
                }
                unsafe impl windows_core::Interface for LanguageModelResponse {
                    type Vtable = <ILanguageModelResponse as windows_core::Interface>::Vtable;
                    const IID: windows_core::GUID =
                        <ILanguageModelResponse as windows_core::Interface>::IID;
                }
                impl windows_core::RuntimeName for LanguageModelResponse {
                    const NAME: &'static str =
                        "Microsoft.Windows.AI.Generative.LanguageModelResponse";
                }
                unsafe impl Send for LanguageModelResponse {}
                unsafe impl Sync for LanguageModelResponse {}
                #[repr(transparent)]
                #[derive(Clone, Copy, Debug, Default, Eq, PartialEq)]
                pub struct LanguageModelResponseStatus(pub i32);
                impl LanguageModelResponseStatus {
                    pub const Complete: Self = Self(0i32);
                    pub const InProgress: Self = Self(1i32);
                    pub const BlockedByPolicy: Self = Self(2i32);
                    pub const PromptLargerThanContext: Self = Self(3i32);
                    pub const PromptBlockedByPolicy: Self = Self(4i32);
                    pub const ResponseBlockedByPolicy: Self = Self(5i32);
                }
                impl windows_core::TypeKind for LanguageModelResponseStatus {
                    type TypeKind = windows_core::CopyType;
                }
                impl windows_core::RuntimeType for LanguageModelResponseStatus {
                    const SIGNATURE: windows_core::imp::ConstBuffer =
                        windows_core::imp::ConstBuffer::from_slice(
                            b"enum(Microsoft.Windows.AI.Generative.LanguageModelResponseStatus;i4)",
                        );
                }
                #[repr(transparent)]
                #[derive(Clone, Copy, Debug, Default, Eq, PartialEq)]
                pub struct LanguageModelSkill(pub i32);
                impl LanguageModelSkill {
                    pub const General: Self = Self(0i32);
                    pub const TextToTable: Self = Self(1i32);
                    pub const Summarize: Self = Self(2i32);
                    pub const Rewrite: Self = Self(3i32);
                }
                impl windows_core::TypeKind for LanguageModelSkill {
                    type TypeKind = windows_core::CopyType;
                }
                impl windows_core::RuntimeType for LanguageModelSkill {
                    const SIGNATURE: windows_core::imp::ConstBuffer =
                        windows_core::imp::ConstBuffer::from_slice(
                            b"enum(Microsoft.Windows.AI.Generative.LanguageModelSkill;i4)",
                        );
                }
            }
        }
    }
}
pub mod Windows {
    pub mod Foundation {
        windows_core::imp::define_interface!(
            IClosable,
            IClosable_Vtbl,
            0x30d5a829_7fa4_4026_83bb_d75bae4ea99e
        );
        impl windows_core::RuntimeType for IClosable {
            const SIGNATURE: windows_core::imp::ConstBuffer =
                windows_core::imp::ConstBuffer::for_interface::<Self>();
        }
        windows_core::imp::interface_hierarchy!(
            IClosable,
            windows_core::IUnknown,
            windows_core::IInspectable
        );
        impl IClosable {
            pub fn Close(&self) -> windows_core::Result<()> {
                let this = self;
                unsafe {
                    (windows_core::Interface::vtable(this).Close)(windows_core::Interface::as_raw(
                        this,
                    ))
                    .ok()
                }
            }
        }
        impl windows_core::RuntimeName for IClosable {
            const NAME: &'static str = "Windows.Foundation.IClosable";
        }
        pub trait IClosable_Impl: windows_core::IUnknownImpl {
            fn Close(&self) -> windows_core::Result<()>;
        }
        impl IClosable_Vtbl {
            pub const fn new<Identity: IClosable_Impl, const OFFSET: isize>() -> Self {
                unsafe extern "system" fn Close<Identity: IClosable_Impl, const OFFSET: isize>(
                    this: *mut core::ffi::c_void,
                ) -> windows_core::HRESULT {
                    unsafe {
                        let this: &Identity =
                            &*((this as *const *const ()).offset(OFFSET) as *const Identity);
                        IClosable_Impl::Close(this).into()
                    }
                }
                Self {
                    base__: windows_core::IInspectable_Vtbl::new::<Identity, IClosable, OFFSET>(),
                    Close: Close::<Identity, OFFSET>,
                }
            }
            pub fn matches(iid: &windows_core::GUID) -> bool {
                iid == &<IClosable as windows_core::Interface>::IID
            }
        }
        #[repr(C)]
        #[doc(hidden)]
        pub struct IClosable_Vtbl {
            pub base__: windows_core::IInspectable_Vtbl,
            pub Close: unsafe extern "system" fn(*mut core::ffi::c_void) -> windows_core::HRESULT,
        }
    }
}
