// Bindings generated by `windows-bindgen` 0.66.0

#![allow(
    non_snake_case,
    non_upper_case_globals,
    non_camel_case_types,
    dead_code,
    clippy::all
)]

#[repr(transparent)]
#[derive(Clone, Debug, Eq, PartialEq)]
pub struct AIFeatureReadyResult(windows_core::IUnknown);
windows_core::imp::interface_hierarchy!(
    AIFeatureReadyResult,
    windows_core::IUnknown,
    windows_core::IInspectable
);
impl AIFeatureReadyResult {
    pub fn Error(&self) -> windows_core::Result<windows_core::HRESULT> {
        let this = self;
        unsafe {
            let mut result__ = core::mem::zeroed();
            (windows_core::Interface::vtable(this).Error)(
                windows_core::Interface::as_raw(this),
                &mut result__,
            )
            .map(|| result__)
        }
    }
    pub fn ErrorDisplayText(&self) -> windows_core::Result<windows_core::HSTRING> {
        let this = self;
        unsafe {
            let mut result__ = core::mem::zeroed();
            (windows_core::Interface::vtable(this).ErrorDisplayText)(
                windows_core::Interface::as_raw(this),
                &mut result__,
            )
            .map(|| core::mem::transmute(result__))
        }
    }
    pub fn ExtendedError(&self) -> windows_core::Result<windows_core::HRESULT> {
        let this = self;
        unsafe {
            let mut result__ = core::mem::zeroed();
            (windows_core::Interface::vtable(this).ExtendedError)(
                windows_core::Interface::as_raw(this),
                &mut result__,
            )
            .map(|| result__)
        }
    }
    pub fn Status(&self) -> windows_core::Result<AIFeatureReadyResultState> {
        let this = self;
        unsafe {
            let mut result__ = core::mem::zeroed();
            (windows_core::Interface::vtable(this).Status)(
                windows_core::Interface::as_raw(this),
                &mut result__,
            )
            .map(|| result__)
        }
    }
    pub fn PackageInstallationFailed(&self) -> windows_core::Result<bool> {
        let this = &windows_core::Interface::cast::<IAIFeatureReadyResult2>(self)?;
        unsafe {
            let mut result__ = core::mem::zeroed();
            (windows_core::Interface::vtable(this).PackageInstallationFailed)(
                windows_core::Interface::as_raw(this),
                &mut result__,
            )
            .map(|| result__)
        }
    }
}
impl windows_core::RuntimeType for AIFeatureReadyResult {
    const SIGNATURE: windows_core::imp::ConstBuffer =
        windows_core::imp::ConstBuffer::for_class::<Self, IAIFeatureReadyResult>();
}
unsafe impl windows_core::Interface for AIFeatureReadyResult {
    type Vtable = <IAIFeatureReadyResult as windows_core::Interface>::Vtable;
    const IID: windows_core::GUID = <IAIFeatureReadyResult as windows_core::Interface>::IID;
}
impl windows_core::RuntimeName for AIFeatureReadyResult {
    const NAME: &'static str = "Microsoft.Windows.AI.AIFeatureReadyResult";
}
unsafe impl Send for AIFeatureReadyResult {}
unsafe impl Sync for AIFeatureReadyResult {}
#[repr(transparent)]
#[derive(Clone, Copy, Debug, Default, Eq, PartialEq)]
pub struct AIFeatureReadyResultState(pub i32);
impl AIFeatureReadyResultState {
    pub const InProgress: Self = Self(0i32);
    pub const Success: Self = Self(1i32);
    pub const Failure: Self = Self(2i32);
}
impl windows_core::TypeKind for AIFeatureReadyResultState {
    type TypeKind = windows_core::CopyType;
}
impl windows_core::RuntimeType for AIFeatureReadyResultState {
    const SIGNATURE: windows_core::imp::ConstBuffer = windows_core::imp::ConstBuffer::from_slice(
        b"enum(Microsoft.Windows.AI.AIFeatureReadyResultState;i4)",
    );
}
#[repr(transparent)]
#[derive(Clone, Copy, Debug, Default, Eq, PartialEq)]
pub struct AIFeatureReadyState(pub i32);
impl AIFeatureReadyState {
    pub const Ready: Self = Self(0i32);
    pub const NotReady: Self = Self(1i32);
    pub const NotSupportedOnCurrentSystem: Self = Self(2i32);
    pub const DisabledByUser: Self = Self(3i32);
}
impl windows_core::TypeKind for AIFeatureReadyState {
    type TypeKind = windows_core::CopyType;
}
impl windows_core::RuntimeType for AIFeatureReadyState {
    const SIGNATURE: windows_core::imp::ConstBuffer = windows_core::imp::ConstBuffer::from_slice(
        b"enum(Microsoft.Windows.AI.AIFeatureReadyState;i4)",
    );
}
#[repr(transparent)]
#[derive(Clone, Debug, Eq, PartialEq)]
pub struct ConversationItem(windows_core::IUnknown);
windows_core::imp::interface_hierarchy!(
    ConversationItem,
    windows_core::IUnknown,
    windows_core::IInspectable
);
impl ConversationItem {
    pub fn new() -> windows_core::Result<Self> {
        Self::IActivationFactory(|f| f.ActivateInstance::<Self>())
    }
    fn IActivationFactory<
        R,
        F: FnOnce(&windows_core::imp::IGenericFactory) -> windows_core::Result<R>,
    >(
        callback: F,
    ) -> windows_core::Result<R> {
        static SHARED: windows_core::imp::FactoryCache<
            ConversationItem,
            windows_core::imp::IGenericFactory,
        > = windows_core::imp::FactoryCache::new();
        SHARED.call(callback)
    }
    pub fn Participant(&self) -> windows_core::Result<windows_core::HSTRING> {
        let this = self;
        unsafe {
            let mut result__ = core::mem::zeroed();
            (windows_core::Interface::vtable(this).Participant)(
                windows_core::Interface::as_raw(this),
                &mut result__,
            )
            .map(|| core::mem::transmute(result__))
        }
    }
    pub fn SetParticipant(&self, value: &windows_core::HSTRING) -> windows_core::Result<()> {
        let this = self;
        unsafe {
            (windows_core::Interface::vtable(this).SetParticipant)(
                windows_core::Interface::as_raw(this),
                core::mem::transmute_copy(value),
            )
            .ok()
        }
    }
    pub fn Message(&self) -> windows_core::Result<windows_core::HSTRING> {
        let this = self;
        unsafe {
            let mut result__ = core::mem::zeroed();
            (windows_core::Interface::vtable(this).Message)(
                windows_core::Interface::as_raw(this),
                &mut result__,
            )
            .map(|| core::mem::transmute(result__))
        }
    }
    pub fn SetMessage(&self, value: &windows_core::HSTRING) -> windows_core::Result<()> {
        let this = self;
        unsafe {
            (windows_core::Interface::vtable(this).SetMessage)(
                windows_core::Interface::as_raw(this),
                core::mem::transmute_copy(value),
            )
            .ok()
        }
    }
}
impl windows_core::RuntimeType for ConversationItem {
    const SIGNATURE: windows_core::imp::ConstBuffer =
        windows_core::imp::ConstBuffer::for_class::<Self, IConversationItem>();
}
unsafe impl windows_core::Interface for ConversationItem {
    type Vtable = <IConversationItem as windows_core::Interface>::Vtable;
    const IID: windows_core::GUID = <IConversationItem as windows_core::Interface>::IID;
}
impl windows_core::RuntimeName for ConversationItem {
    const NAME: &'static str = "Microsoft.Windows.AI.Text.ConversationItem";
}
unsafe impl Send for ConversationItem {}
unsafe impl Sync for ConversationItem {}
#[repr(transparent)]
#[derive(Clone, Debug, Eq, PartialEq)]
pub struct ConversationSummaryOptions(windows_core::IUnknown);
windows_core::imp::interface_hierarchy!(
    ConversationSummaryOptions,
    windows_core::IUnknown,
    windows_core::IInspectable
);
impl ConversationSummaryOptions {
    pub fn new() -> windows_core::Result<Self> {
        Self::IActivationFactory(|f| f.ActivateInstance::<Self>())
    }
    fn IActivationFactory<
        R,
        F: FnOnce(&windows_core::imp::IGenericFactory) -> windows_core::Result<R>,
    >(
        callback: F,
    ) -> windows_core::Result<R> {
        static SHARED: windows_core::imp::FactoryCache<
            ConversationSummaryOptions,
            windows_core::imp::IGenericFactory,
        > = windows_core::imp::FactoryCache::new();
        SHARED.call(callback)
    }
    pub fn InputKind(&self) -> windows_core::Result<InputKind> {
        let this = self;
        unsafe {
            let mut result__ = core::mem::zeroed();
            (windows_core::Interface::vtable(this).InputKind)(
                windows_core::Interface::as_raw(this),
                &mut result__,
            )
            .map(|| result__)
        }
    }
    pub fn SetInputKind(&self, value: InputKind) -> windows_core::Result<()> {
        let this = self;
        unsafe {
            (windows_core::Interface::vtable(this).SetInputKind)(
                windows_core::Interface::as_raw(this),
                value,
            )
            .ok()
        }
    }
    pub fn IncludeMessageCitations(&self) -> windows_core::Result<bool> {
        let this = self;
        unsafe {
            let mut result__ = core::mem::zeroed();
            (windows_core::Interface::vtable(this).IncludeMessageCitations)(
                windows_core::Interface::as_raw(this),
                &mut result__,
            )
            .map(|| result__)
        }
    }
    pub fn SetIncludeMessageCitations(&self, value: bool) -> windows_core::Result<()> {
        let this = self;
        unsafe {
            (windows_core::Interface::vtable(this).SetIncludeMessageCitations)(
                windows_core::Interface::as_raw(this),
                value,
            )
            .ok()
        }
    }
    pub fn IncludeParticipantAttribution(&self) -> windows_core::Result<bool> {
        let this = self;
        unsafe {
            let mut result__ = core::mem::zeroed();
            (windows_core::Interface::vtable(this).IncludeParticipantAttribution)(
                windows_core::Interface::as_raw(this),
                &mut result__,
            )
            .map(|| result__)
        }
    }
    pub fn SetIncludeParticipantAttribution(&self, value: bool) -> windows_core::Result<()> {
        let this = self;
        unsafe {
            (windows_core::Interface::vtable(this).SetIncludeParticipantAttribution)(
                windows_core::Interface::as_raw(this),
                value,
            )
            .ok()
        }
    }
    pub fn MaxKeyPoints(&self) -> windows_core::Result<u32> {
        let this = self;
        unsafe {
            let mut result__ = core::mem::zeroed();
            (windows_core::Interface::vtable(this).MaxKeyPoints)(
                windows_core::Interface::as_raw(this),
                &mut result__,
            )
            .map(|| result__)
        }
    }
    pub fn SetMaxKeyPoints(&self, value: u32) -> windows_core::Result<()> {
        let this = self;
        unsafe {
            (windows_core::Interface::vtable(this).SetMaxKeyPoints)(
                windows_core::Interface::as_raw(this),
                value,
            )
            .ok()
        }
    }
    pub fn Language(&self) -> windows_core::Result<windows_core::HSTRING> {
        let this = self;
        unsafe {
            let mut result__ = core::mem::zeroed();
            (windows_core::Interface::vtable(this).Language)(
                windows_core::Interface::as_raw(this),
                &mut result__,
            )
            .map(|| core::mem::transmute(result__))
        }
    }
    pub fn SetLanguage(&self, value: &windows_core::HSTRING) -> windows_core::Result<()> {
        let this = self;
        unsafe {
            (windows_core::Interface::vtable(this).SetLanguage)(
                windows_core::Interface::as_raw(this),
                core::mem::transmute_copy(value),
            )
            .ok()
        }
    }
}
impl windows_core::RuntimeType for ConversationSummaryOptions {
    const SIGNATURE: windows_core::imp::ConstBuffer =
        windows_core::imp::ConstBuffer::for_class::<Self, IConversationSummaryOptions>();
}
unsafe impl windows_core::Interface for ConversationSummaryOptions {
    type Vtable = <IConversationSummaryOptions as windows_core::Interface>::Vtable;
    const IID: windows_core::GUID = <IConversationSummaryOptions as windows_core::Interface>::IID;
}
impl windows_core::RuntimeName for ConversationSummaryOptions {
    const NAME: &'static str = "Microsoft.Windows.AI.Text.ConversationSummaryOptions";
}
unsafe impl Send for ConversationSummaryOptions {}
unsafe impl Sync for ConversationSummaryOptions {}
windows_core::imp::define_interface!(
    IAIFeatureReadyResult,
    IAIFeatureReadyResult_Vtbl,
    0x936a78a6_c242_5937_9814_e512d4193a6d
);
impl windows_core::RuntimeType for IAIFeatureReadyResult {
    const SIGNATURE: windows_core::imp::ConstBuffer =
        windows_core::imp::ConstBuffer::for_interface::<Self>();
}
#[repr(C)]
#[doc(hidden)]
pub struct IAIFeatureReadyResult_Vtbl {
    pub base__: windows_core::IInspectable_Vtbl,
    pub Error: unsafe extern "system" fn(
        *mut core::ffi::c_void,
        *mut windows_core::HRESULT,
    ) -> windows_core::HRESULT,
    pub ErrorDisplayText: unsafe extern "system" fn(
        *mut core::ffi::c_void,
        *mut *mut core::ffi::c_void,
    ) -> windows_core::HRESULT,
    pub ExtendedError: unsafe extern "system" fn(
        *mut core::ffi::c_void,
        *mut windows_core::HRESULT,
    ) -> windows_core::HRESULT,
    pub Status: unsafe extern "system" fn(
        *mut core::ffi::c_void,
        *mut AIFeatureReadyResultState,
    ) -> windows_core::HRESULT,
}
windows_core::imp::define_interface!(
    IAIFeatureReadyResult2,
    IAIFeatureReadyResult2_Vtbl,
    0xec5f1d67_43c1_5bdb_b9f4_a0c7110582cb
);
impl windows_core::RuntimeType for IAIFeatureReadyResult2 {
    const SIGNATURE: windows_core::imp::ConstBuffer =
        windows_core::imp::ConstBuffer::for_interface::<Self>();
}
#[repr(C)]
#[doc(hidden)]
pub struct IAIFeatureReadyResult2_Vtbl {
    pub base__: windows_core::IInspectable_Vtbl,
    pub PackageInstallationFailed:
        unsafe extern "system" fn(*mut core::ffi::c_void, *mut bool) -> windows_core::HRESULT,
}
windows_core::imp::define_interface!(
    IClosable,
    IClosable_Vtbl,
    0x30d5a829_7fa4_4026_83bb_d75bae4ea99e
);
impl windows_core::RuntimeType for IClosable {
    const SIGNATURE: windows_core::imp::ConstBuffer =
        windows_core::imp::ConstBuffer::for_interface::<Self>();
}
windows_core::imp::interface_hierarchy!(
    IClosable,
    windows_core::IUnknown,
    windows_core::IInspectable
);
impl IClosable {
    pub fn Close(&self) -> windows_core::Result<()> {
        let this = self;
        unsafe {
            (windows_core::Interface::vtable(this).Close)(windows_core::Interface::as_raw(this))
                .ok()
        }
    }
}
impl windows_core::RuntimeName for IClosable {
    const NAME: &'static str = "Windows.Foundation.IClosable";
}
pub trait IClosable_Impl: windows_core::IUnknownImpl {
    fn Close(&self) -> windows_core::Result<()>;
}
impl IClosable_Vtbl {
    pub const fn new<Identity: IClosable_Impl, const OFFSET: isize>() -> Self {
        unsafe extern "system" fn Close<Identity: IClosable_Impl, const OFFSET: isize>(
            this: *mut core::ffi::c_void,
        ) -> windows_core::HRESULT {
            unsafe {
                let this: &Identity =
                    &*((this as *const *const ()).offset(OFFSET) as *const Identity);
                IClosable_Impl::Close(this).into()
            }
        }
        Self {
            base__: windows_core::IInspectable_Vtbl::new::<Identity, IClosable, OFFSET>(),
            Close: Close::<Identity, OFFSET>,
        }
    }
    pub fn matches(iid: &windows_core::GUID) -> bool {
        iid == &<IClosable as windows_core::Interface>::IID
    }
}
#[repr(C)]
#[doc(hidden)]
pub struct IClosable_Vtbl {
    pub base__: windows_core::IInspectable_Vtbl,
    pub Close: unsafe extern "system" fn(*mut core::ffi::c_void) -> windows_core::HRESULT,
}
windows_core::imp::define_interface!(
    IConversationItem,
    IConversationItem_Vtbl,
    0x957b0b85_4d7e_5788_baae_af7cf256bb8e
);
impl windows_core::RuntimeType for IConversationItem {
    const SIGNATURE: windows_core::imp::ConstBuffer =
        windows_core::imp::ConstBuffer::for_interface::<Self>();
}
#[repr(C)]
#[doc(hidden)]
pub struct IConversationItem_Vtbl {
    pub base__: windows_core::IInspectable_Vtbl,
    pub Participant: unsafe extern "system" fn(
        *mut core::ffi::c_void,
        *mut *mut core::ffi::c_void,
    ) -> windows_core::HRESULT,
    pub SetParticipant: unsafe extern "system" fn(
        *mut core::ffi::c_void,
        *mut core::ffi::c_void,
    ) -> windows_core::HRESULT,
    pub Message: unsafe extern "system" fn(
        *mut core::ffi::c_void,
        *mut *mut core::ffi::c_void,
    ) -> windows_core::HRESULT,
    pub SetMessage: unsafe extern "system" fn(
        *mut core::ffi::c_void,
        *mut core::ffi::c_void,
    ) -> windows_core::HRESULT,
}
windows_core::imp::define_interface!(
    IConversationSummaryOptions,
    IConversationSummaryOptions_Vtbl,
    0x360bce9f_fd14_5d0e_bd24_fd78ed3038e6
);
impl windows_core::RuntimeType for IConversationSummaryOptions {
    const SIGNATURE: windows_core::imp::ConstBuffer =
        windows_core::imp::ConstBuffer::for_interface::<Self>();
}
#[repr(C)]
#[doc(hidden)]
pub struct IConversationSummaryOptions_Vtbl {
    pub base__: windows_core::IInspectable_Vtbl,
    pub InputKind:
        unsafe extern "system" fn(*mut core::ffi::c_void, *mut InputKind) -> windows_core::HRESULT,
    pub SetInputKind:
        unsafe extern "system" fn(*mut core::ffi::c_void, InputKind) -> windows_core::HRESULT,
    pub IncludeMessageCitations:
        unsafe extern "system" fn(*mut core::ffi::c_void, *mut bool) -> windows_core::HRESULT,
    pub SetIncludeMessageCitations:
        unsafe extern "system" fn(*mut core::ffi::c_void, bool) -> windows_core::HRESULT,
    pub IncludeParticipantAttribution:
        unsafe extern "system" fn(*mut core::ffi::c_void, *mut bool) -> windows_core::HRESULT,
    pub SetIncludeParticipantAttribution:
        unsafe extern "system" fn(*mut core::ffi::c_void, bool) -> windows_core::HRESULT,
    pub MaxKeyPoints:
        unsafe extern "system" fn(*mut core::ffi::c_void, *mut u32) -> windows_core::HRESULT,
    pub SetMaxKeyPoints:
        unsafe extern "system" fn(*mut core::ffi::c_void, u32) -> windows_core::HRESULT,
    pub Language: unsafe extern "system" fn(
        *mut core::ffi::c_void,
        *mut *mut core::ffi::c_void,
    ) -> windows_core::HRESULT,
    pub SetLanguage: unsafe extern "system" fn(
        *mut core::ffi::c_void,
        *mut core::ffi::c_void,
    ) -> windows_core::HRESULT,
}
windows_core::imp::define_interface!(
    ILanguageModel,
    ILanguageModel_Vtbl,
    0x6331c629_8c86_5bfe_8c4e_9ca5573cc14b
);
impl windows_core::RuntimeType for ILanguageModel {
    const SIGNATURE: windows_core::imp::ConstBuffer =
        windows_core::imp::ConstBuffer::for_interface::<Self>();
}
#[repr(C)]
#[doc(hidden)]
pub struct ILanguageModel_Vtbl {
    pub base__: windows_core::IInspectable_Vtbl,
}
windows_core::imp::define_interface!(
    ILanguageModel2,
    ILanguageModel2_Vtbl,
    0x653b714e_f9b3_51cb_954f_5ea58f63ab89
);
impl windows_core::RuntimeType for ILanguageModel2 {
    const SIGNATURE: windows_core::imp::ConstBuffer =
        windows_core::imp::ConstBuffer::for_interface::<Self>();
}
#[repr(C)]
#[doc(hidden)]
pub struct ILanguageModel2_Vtbl {
    pub base__: windows_core::IInspectable_Vtbl,
    pub GenerateResponseAsync: unsafe extern "system" fn(
        *mut core::ffi::c_void,
        *mut core::ffi::c_void,
        *mut *mut core::ffi::c_void,
    ) -> windows_core::HRESULT,
    pub GenerateResponseAsync2: unsafe extern "system" fn(
        *mut core::ffi::c_void,
        *mut core::ffi::c_void,
        *mut core::ffi::c_void,
        *mut *mut core::ffi::c_void,
    ) -> windows_core::HRESULT,
    pub GenerateResponseAsync3: unsafe extern "system" fn(
        *mut core::ffi::c_void,
        *mut core::ffi::c_void,
        *mut core::ffi::c_void,
        *mut core::ffi::c_void,
        *mut *mut core::ffi::c_void,
    ) -> windows_core::HRESULT,
    GenerateResponseFromEmbeddingsAsync: usize,
    GenerateResponseFromEmbeddingsAsync2: usize,
    GenerateResponseFromEmbeddingsAsync3: usize,
    pub GenerateEmbeddingVectors: unsafe extern "system" fn(
        *mut core::ffi::c_void,
        *mut core::ffi::c_void,
        *mut *mut core::ffi::c_void,
    ) -> windows_core::HRESULT,
    GenerateEmbeddingVectors2: usize,
    pub GetUsablePromptLength: unsafe extern "system" fn(
        *mut core::ffi::c_void,
        *mut core::ffi::c_void,
        *mut u64,
    ) -> windows_core::HRESULT,
    pub GetUsablePromptLength2: unsafe extern "system" fn(
        *mut core::ffi::c_void,
        *mut core::ffi::c_void,
        *mut core::ffi::c_void,
        *mut u64,
    ) -> windows_core::HRESULT,
    pub GetVectorSpaceId: unsafe extern "system" fn(
        *mut core::ffi::c_void,
        *mut windows_core::GUID,
    ) -> windows_core::HRESULT,
    pub CreateContext: unsafe extern "system" fn(
        *mut core::ffi::c_void,
        *mut *mut core::ffi::c_void,
    ) -> windows_core::HRESULT,
    pub CreateContext2: unsafe extern "system" fn(
        *mut core::ffi::c_void,
        *mut core::ffi::c_void,
        *mut *mut core::ffi::c_void,
    ) -> windows_core::HRESULT,
    CreateContext3: usize,
}
windows_core::imp::define_interface!(
    ILanguageModelContext,
    ILanguageModelContext_Vtbl,
    0x518b305c_7b69_5a33_8129_d47d6b8eec4e
);
impl windows_core::RuntimeType for ILanguageModelContext {
    const SIGNATURE: windows_core::imp::ConstBuffer =
        windows_core::imp::ConstBuffer::for_interface::<Self>();
}
#[repr(C)]
#[doc(hidden)]
pub struct ILanguageModelContext_Vtbl {
    pub base__: windows_core::IInspectable_Vtbl,
}
windows_core::imp::define_interface!(
    ILanguageModelEmbeddingVectorResult,
    ILanguageModelEmbeddingVectorResult_Vtbl,
    0x4dbdb154_ee3c_56f6_a40b_413e95bd5acb
);
impl windows_core::RuntimeType for ILanguageModelEmbeddingVectorResult {
    const SIGNATURE: windows_core::imp::ConstBuffer =
        windows_core::imp::ConstBuffer::for_interface::<Self>();
}
#[repr(C)]
#[doc(hidden)]
pub struct ILanguageModelEmbeddingVectorResult_Vtbl {
    pub base__: windows_core::IInspectable_Vtbl,
    EmbeddingVectors: usize,
    pub Status: unsafe extern "system" fn(
        *mut core::ffi::c_void,
        *mut LanguageModelResponseStatus,
    ) -> windows_core::HRESULT,
    pub ExtendedError: unsafe extern "system" fn(
        *mut core::ffi::c_void,
        *mut windows_core::HRESULT,
    ) -> windows_core::HRESULT,
}
windows_core::imp::define_interface!(
    ILanguageModelOptions,
    ILanguageModelOptions_Vtbl,
    0x7f380003_5a09_5f1f_afb0_aa483e3670cc
);
impl windows_core::RuntimeType for ILanguageModelOptions {
    const SIGNATURE: windows_core::imp::ConstBuffer =
        windows_core::imp::ConstBuffer::for_interface::<Self>();
}
#[repr(C)]
#[doc(hidden)]
pub struct ILanguageModelOptions_Vtbl {
    pub base__: windows_core::IInspectable_Vtbl,
    pub Temperature:
        unsafe extern "system" fn(*mut core::ffi::c_void, *mut f32) -> windows_core::HRESULT,
    pub SetTemperature:
        unsafe extern "system" fn(*mut core::ffi::c_void, f32) -> windows_core::HRESULT,
    pub TopP: unsafe extern "system" fn(*mut core::ffi::c_void, *mut f32) -> windows_core::HRESULT,
    pub SetTopP: unsafe extern "system" fn(*mut core::ffi::c_void, f32) -> windows_core::HRESULT,
    pub TopK: unsafe extern "system" fn(*mut core::ffi::c_void, *mut u32) -> windows_core::HRESULT,
    pub SetTopK: unsafe extern "system" fn(*mut core::ffi::c_void, u32) -> windows_core::HRESULT,
    ContentFilterOptions: usize,
    SetContentFilterOptions: usize,
}
windows_core::imp::define_interface!(
    ILanguageModelResponseResult,
    ILanguageModelResponseResult_Vtbl,
    0x3a256fff_a426_5d3b_8e4b_3ac84162471e
);
impl windows_core::RuntimeType for ILanguageModelResponseResult {
    const SIGNATURE: windows_core::imp::ConstBuffer =
        windows_core::imp::ConstBuffer::for_interface::<Self>();
}
#[repr(C)]
#[doc(hidden)]
pub struct ILanguageModelResponseResult_Vtbl {
    pub base__: windows_core::IInspectable_Vtbl,
    pub Text: unsafe extern "system" fn(
        *mut core::ffi::c_void,
        *mut *mut core::ffi::c_void,
    ) -> windows_core::HRESULT,
    pub Status: unsafe extern "system" fn(
        *mut core::ffi::c_void,
        *mut LanguageModelResponseStatus,
    ) -> windows_core::HRESULT,
    pub ExtendedError: unsafe extern "system" fn(
        *mut core::ffi::c_void,
        *mut windows_core::HRESULT,
    ) -> windows_core::HRESULT,
}
windows_core::imp::define_interface!(
    ILanguageModelStatics,
    ILanguageModelStatics_Vtbl,
    0x8f18f9af_6095_553b_8d9d_6bcc98026546
);
impl windows_core::RuntimeType for ILanguageModelStatics {
    const SIGNATURE: windows_core::imp::ConstBuffer =
        windows_core::imp::ConstBuffer::for_interface::<Self>();
}
#[repr(C)]
#[doc(hidden)]
pub struct ILanguageModelStatics_Vtbl {
    pub base__: windows_core::IInspectable_Vtbl,
    pub GetReadyState: unsafe extern "system" fn(
        *mut core::ffi::c_void,
        *mut AIFeatureReadyState,
    ) -> windows_core::HRESULT,
    pub EnsureReadyAsync: unsafe extern "system" fn(
        *mut core::ffi::c_void,
        *mut *mut core::ffi::c_void,
    ) -> windows_core::HRESULT,
    pub CreateAsync: unsafe extern "system" fn(
        *mut core::ffi::c_void,
        *mut *mut core::ffi::c_void,
    ) -> windows_core::HRESULT,
}
windows_core::imp::define_interface!(
    ITextRewriter,
    ITextRewriter_Vtbl,
    0xeb1e7cf0_e110_506c_b0ea_7a288d8e7778
);
impl windows_core::RuntimeType for ITextRewriter {
    const SIGNATURE: windows_core::imp::ConstBuffer =
        windows_core::imp::ConstBuffer::for_interface::<Self>();
}
#[repr(C)]
#[doc(hidden)]
pub struct ITextRewriter_Vtbl {
    pub base__: windows_core::IInspectable_Vtbl,
    pub RewriteAsync: unsafe extern "system" fn(
        *mut core::ffi::c_void,
        *mut core::ffi::c_void,
        *mut *mut core::ffi::c_void,
    ) -> windows_core::HRESULT,
}
windows_core::imp::define_interface!(
    ITextRewriter2,
    ITextRewriter2_Vtbl,
    0x7937d261_13ce_5b24_b17c_fe5cd0be23b6
);
impl windows_core::RuntimeType for ITextRewriter2 {
    const SIGNATURE: windows_core::imp::ConstBuffer =
        windows_core::imp::ConstBuffer::for_interface::<Self>();
}
#[repr(C)]
#[doc(hidden)]
pub struct ITextRewriter2_Vtbl {
    pub base__: windows_core::IInspectable_Vtbl,
    pub RewriteAsync: unsafe extern "system" fn(
        *mut core::ffi::c_void,
        *mut core::ffi::c_void,
        TextRewriteTone,
        *mut *mut core::ffi::c_void,
    ) -> windows_core::HRESULT,
}
windows_core::imp::define_interface!(
    ITextRewriter3,
    ITextRewriter3_Vtbl,
    0x622eb80a_ed1a_5525_80d8_c6e80236a195
);
impl windows_core::RuntimeType for ITextRewriter3 {
    const SIGNATURE: windows_core::imp::ConstBuffer =
        windows_core::imp::ConstBuffer::for_interface::<Self>();
}
#[repr(C)]
#[doc(hidden)]
pub struct ITextRewriter3_Vtbl {
    pub base__: windows_core::IInspectable_Vtbl,
    pub RewriteCustomAsync: unsafe extern "system" fn(
        *mut core::ffi::c_void,
        *mut core::ffi::c_void,
        *mut core::ffi::c_void,
        *mut *mut core::ffi::c_void,
    ) -> windows_core::HRESULT,
}
windows_core::imp::define_interface!(
    ITextRewriterFactory,
    ITextRewriterFactory_Vtbl,
    0xf452e60d_ef50_5bc9_b483_217d5b4e7151
);
impl windows_core::RuntimeType for ITextRewriterFactory {
    const SIGNATURE: windows_core::imp::ConstBuffer =
        windows_core::imp::ConstBuffer::for_interface::<Self>();
}
#[repr(C)]
#[doc(hidden)]
pub struct ITextRewriterFactory_Vtbl {
    pub base__: windows_core::IInspectable_Vtbl,
    pub CreateInstance: unsafe extern "system" fn(
        *mut core::ffi::c_void,
        *mut core::ffi::c_void,
        *mut *mut core::ffi::c_void,
    ) -> windows_core::HRESULT,
}
windows_core::imp::define_interface!(
    ITextSummarizer,
    ITextSummarizer_Vtbl,
    0xeef548c5_d7bc_50be_a8ab_29e241b78bd1
);
impl windows_core::RuntimeType for ITextSummarizer {
    const SIGNATURE: windows_core::imp::ConstBuffer =
        windows_core::imp::ConstBuffer::for_interface::<Self>();
}
#[repr(C)]
#[doc(hidden)]
pub struct ITextSummarizer_Vtbl {
    pub base__: windows_core::IInspectable_Vtbl,
    pub SummarizeAsync: unsafe extern "system" fn(
        *mut core::ffi::c_void,
        *mut core::ffi::c_void,
        *mut *mut core::ffi::c_void,
    ) -> windows_core::HRESULT,
    pub SummarizeParagraphAsync: unsafe extern "system" fn(
        *mut core::ffi::c_void,
        *mut core::ffi::c_void,
        *mut *mut core::ffi::c_void,
    ) -> windows_core::HRESULT,
}
windows_core::imp::define_interface!(
    ITextSummarizer2,
    ITextSummarizer2_Vtbl,
    0x9e20797d_1ff6_5295_8cb6_d48fb8ba483b
);
impl windows_core::RuntimeType for ITextSummarizer2 {
    const SIGNATURE: windows_core::imp::ConstBuffer =
        windows_core::imp::ConstBuffer::for_interface::<Self>();
}
#[repr(C)]
#[doc(hidden)]
pub struct ITextSummarizer2_Vtbl {
    pub base__: windows_core::IInspectable_Vtbl,
    pub SummarizeConversationAsync: unsafe extern "system" fn(
        *mut core::ffi::c_void,
        *mut core::ffi::c_void,
        *mut core::ffi::c_void,
        *mut *mut core::ffi::c_void,
    ) -> windows_core::HRESULT,
}
windows_core::imp::define_interface!(
    ITextSummarizer3,
    ITextSummarizer3_Vtbl,
    0x493d32b9_dbc9_5d4b_802f_90473850500e
);
impl windows_core::RuntimeType for ITextSummarizer3 {
    const SIGNATURE: windows_core::imp::ConstBuffer =
        windows_core::imp::ConstBuffer::for_interface::<Self>();
}
#[repr(C)]
#[doc(hidden)]
pub struct ITextSummarizer3_Vtbl {
    pub base__: windows_core::IInspectable_Vtbl,
    pub IsPromptLargerThanContext: unsafe extern "system" fn(
        *mut core::ffi::c_void,
        u32,
        *const ConversationItem,
        *mut core::ffi::c_void,
        *mut u64,
        *mut bool,
    ) -> windows_core::HRESULT,
}
windows_core::imp::define_interface!(
    ITextSummarizer4,
    ITextSummarizer4_Vtbl,
    0x5b7a28c0_7777_52e5_9934_b95b514cf535
);
impl windows_core::RuntimeType for ITextSummarizer4 {
    const SIGNATURE: windows_core::imp::ConstBuffer =
        windows_core::imp::ConstBuffer::for_interface::<Self>();
}
#[repr(C)]
#[doc(hidden)]
pub struct ITextSummarizer4_Vtbl {
    pub base__: windows_core::IInspectable_Vtbl,
    pub IsPromptLargerThanContext: unsafe extern "system" fn(
        *mut core::ffi::c_void,
        *mut core::ffi::c_void,
        *mut u64,
        *mut bool,
    ) -> windows_core::HRESULT,
}
windows_core::imp::define_interface!(
    ITextSummarizerFactory,
    ITextSummarizerFactory_Vtbl,
    0xb6a75913_4a1e_59e7_856a_ae7ab2383864
);
impl windows_core::RuntimeType for ITextSummarizerFactory {
    const SIGNATURE: windows_core::imp::ConstBuffer =
        windows_core::imp::ConstBuffer::for_interface::<Self>();
}
#[repr(C)]
#[doc(hidden)]
pub struct ITextSummarizerFactory_Vtbl {
    pub base__: windows_core::IInspectable_Vtbl,
    pub CreateInstance: unsafe extern "system" fn(
        *mut core::ffi::c_void,
        *mut core::ffi::c_void,
        *mut *mut core::ffi::c_void,
    ) -> windows_core::HRESULT,
}
windows_core::imp::define_interface!(
    ITextToTableConverter,
    ITextToTableConverter_Vtbl,
    0xa008d9ad_25ce_5a6b_9ceb_d8e95d04e10b
);
impl windows_core::RuntimeType for ITextToTableConverter {
    const SIGNATURE: windows_core::imp::ConstBuffer =
        windows_core::imp::ConstBuffer::for_interface::<Self>();
}
#[repr(C)]
#[doc(hidden)]
pub struct ITextToTableConverter_Vtbl {
    pub base__: windows_core::IInspectable_Vtbl,
    pub ConvertAsync: unsafe extern "system" fn(
        *mut core::ffi::c_void,
        *mut core::ffi::c_void,
        *mut *mut core::ffi::c_void,
    ) -> windows_core::HRESULT,
}
windows_core::imp::define_interface!(
    ITextToTableConverterFactory,
    ITextToTableConverterFactory_Vtbl,
    0xbb84cbb5_19c8_5857_b65d_705aa1486404
);
impl windows_core::RuntimeType for ITextToTableConverterFactory {
    const SIGNATURE: windows_core::imp::ConstBuffer =
        windows_core::imp::ConstBuffer::for_interface::<Self>();
}
#[repr(C)]
#[doc(hidden)]
pub struct ITextToTableConverterFactory_Vtbl {
    pub base__: windows_core::IInspectable_Vtbl,
    pub CreateInstance: unsafe extern "system" fn(
        *mut core::ffi::c_void,
        *mut core::ffi::c_void,
        *mut *mut core::ffi::c_void,
    ) -> windows_core::HRESULT,
}
windows_core::imp::define_interface!(
    ITextToTableResponseResult,
    ITextToTableResponseResult_Vtbl,
    0x391fbf11_59cd_575d_834a_9ef823116f98
);
impl windows_core::RuntimeType for ITextToTableResponseResult {
    const SIGNATURE: windows_core::imp::ConstBuffer =
        windows_core::imp::ConstBuffer::for_interface::<Self>();
}
#[repr(C)]
#[doc(hidden)]
pub struct ITextToTableResponseResult_Vtbl {
    pub base__: windows_core::IInspectable_Vtbl,
    pub GetRows: unsafe extern "system" fn(
        *mut core::ffi::c_void,
        *mut u32,
        *mut *mut *mut core::ffi::c_void,
    ) -> windows_core::HRESULT,
    pub Status: unsafe extern "system" fn(
        *mut core::ffi::c_void,
        *mut LanguageModelResponseStatus,
    ) -> windows_core::HRESULT,
    pub ExtendedError: unsafe extern "system" fn(
        *mut core::ffi::c_void,
        *mut windows_core::HRESULT,
    ) -> windows_core::HRESULT,
}
windows_core::imp::define_interface!(
    ITextToTableRow,
    ITextToTableRow_Vtbl,
    0x036294fe_e53c_5e66_93d2_7c92338db881
);
impl windows_core::RuntimeType for ITextToTableRow {
    const SIGNATURE: windows_core::imp::ConstBuffer =
        windows_core::imp::ConstBuffer::for_interface::<Self>();
}
#[repr(C)]
#[doc(hidden)]
pub struct ITextToTableRow_Vtbl {
    pub base__: windows_core::IInspectable_Vtbl,
    pub GetColumns: unsafe extern "system" fn(
        *mut core::ffi::c_void,
        *mut u32,
        *mut *mut *mut core::ffi::c_void,
    ) -> windows_core::HRESULT,
}
#[repr(transparent)]
#[derive(Clone, Copy, Debug, Default, Eq, PartialEq)]
pub struct InputKind(pub i32);
impl InputKind {
    pub const GeneralConversation: Self = Self(0i32);
    pub const Email: Self = Self(1i32);
}
impl windows_core::TypeKind for InputKind {
    type TypeKind = windows_core::CopyType;
}
impl windows_core::RuntimeType for InputKind {
    const SIGNATURE: windows_core::imp::ConstBuffer =
        windows_core::imp::ConstBuffer::from_slice(b"enum(Microsoft.Windows.AI.Text.InputKind;i4)");
}
#[repr(transparent)]
#[derive(Clone, Debug, Eq, PartialEq)]
pub struct LanguageModel(windows_core::IUnknown);
windows_core::imp::interface_hierarchy!(
    LanguageModel,
    windows_core::IUnknown,
    windows_core::IInspectable
);
windows_core::imp::required_hierarchy!(LanguageModel, IClosable);
impl LanguageModel {
    pub fn Close(&self) -> windows_core::Result<()> {
        let this = &windows_core::Interface::cast::<IClosable>(self)?;
        unsafe {
            (windows_core::Interface::vtable(this).Close)(windows_core::Interface::as_raw(this))
                .ok()
        }
    }
    pub fn GenerateResponseAsync(
        &self,
        prompt: &windows_core::HSTRING,
    ) -> windows_core::Result<
        windows_future::IAsyncOperationWithProgress<
            LanguageModelResponseResult,
            windows_core::HSTRING,
        >,
    > {
        let this = &windows_core::Interface::cast::<ILanguageModel2>(self)?;
        unsafe {
            let mut result__ = core::mem::zeroed();
            (windows_core::Interface::vtable(this).GenerateResponseAsync)(
                windows_core::Interface::as_raw(this),
                core::mem::transmute_copy(prompt),
                &mut result__,
            )
            .and_then(|| windows_core::Type::from_abi(result__))
        }
    }
    pub fn GenerateResponseAsync2<P1>(
        &self,
        prompt: &windows_core::HSTRING,
        options: P1,
    ) -> windows_core::Result<
        windows_future::IAsyncOperationWithProgress<
            LanguageModelResponseResult,
            windows_core::HSTRING,
        >,
    >
    where
        P1: windows_core::Param<LanguageModelOptions>,
    {
        let this = &windows_core::Interface::cast::<ILanguageModel2>(self)?;
        unsafe {
            let mut result__ = core::mem::zeroed();
            (windows_core::Interface::vtable(this).GenerateResponseAsync2)(
                windows_core::Interface::as_raw(this),
                core::mem::transmute_copy(prompt),
                options.param().abi(),
                &mut result__,
            )
            .and_then(|| windows_core::Type::from_abi(result__))
        }
    }
    pub fn GenerateResponseAsync3<P0, P2>(
        &self,
        context: P0,
        prompt: &windows_core::HSTRING,
        options: P2,
    ) -> windows_core::Result<
        windows_future::IAsyncOperationWithProgress<
            LanguageModelResponseResult,
            windows_core::HSTRING,
        >,
    >
    where
        P0: windows_core::Param<LanguageModelContext>,
        P2: windows_core::Param<LanguageModelOptions>,
    {
        let this = &windows_core::Interface::cast::<ILanguageModel2>(self)?;
        unsafe {
            let mut result__ = core::mem::zeroed();
            (windows_core::Interface::vtable(this).GenerateResponseAsync3)(
                windows_core::Interface::as_raw(this),
                context.param().abi(),
                core::mem::transmute_copy(prompt),
                options.param().abi(),
                &mut result__,
            )
            .and_then(|| windows_core::Type::from_abi(result__))
        }
    }
    pub fn GenerateEmbeddingVectors(
        &self,
        prompt: &windows_core::HSTRING,
    ) -> windows_core::Result<LanguageModelEmbeddingVectorResult> {
        let this = &windows_core::Interface::cast::<ILanguageModel2>(self)?;
        unsafe {
            let mut result__ = core::mem::zeroed();
            (windows_core::Interface::vtable(this).GenerateEmbeddingVectors)(
                windows_core::Interface::as_raw(this),
                core::mem::transmute_copy(prompt),
                &mut result__,
            )
            .and_then(|| windows_core::Type::from_abi(result__))
        }
    }
    pub fn GetUsablePromptLength(
        &self,
        prompt: &windows_core::HSTRING,
    ) -> windows_core::Result<u64> {
        let this = &windows_core::Interface::cast::<ILanguageModel2>(self)?;
        unsafe {
            let mut result__ = core::mem::zeroed();
            (windows_core::Interface::vtable(this).GetUsablePromptLength)(
                windows_core::Interface::as_raw(this),
                core::mem::transmute_copy(prompt),
                &mut result__,
            )
            .map(|| result__)
        }
    }
    pub fn GetUsablePromptLength2<P0>(
        &self,
        context: P0,
        prompt: &windows_core::HSTRING,
    ) -> windows_core::Result<u64>
    where
        P0: windows_core::Param<LanguageModelContext>,
    {
        let this = &windows_core::Interface::cast::<ILanguageModel2>(self)?;
        unsafe {
            let mut result__ = core::mem::zeroed();
            (windows_core::Interface::vtable(this).GetUsablePromptLength2)(
                windows_core::Interface::as_raw(this),
                context.param().abi(),
                core::mem::transmute_copy(prompt),
                &mut result__,
            )
            .map(|| result__)
        }
    }
    pub fn GetVectorSpaceId(&self) -> windows_core::Result<windows_core::GUID> {
        let this = &windows_core::Interface::cast::<ILanguageModel2>(self)?;
        unsafe {
            let mut result__ = core::mem::zeroed();
            (windows_core::Interface::vtable(this).GetVectorSpaceId)(
                windows_core::Interface::as_raw(this),
                &mut result__,
            )
            .map(|| result__)
        }
    }
    pub fn CreateContext(&self) -> windows_core::Result<LanguageModelContext> {
        let this = &windows_core::Interface::cast::<ILanguageModel2>(self)?;
        unsafe {
            let mut result__ = core::mem::zeroed();
            (windows_core::Interface::vtable(this).CreateContext)(
                windows_core::Interface::as_raw(this),
                &mut result__,
            )
            .and_then(|| windows_core::Type::from_abi(result__))
        }
    }
    pub fn CreateContext2(
        &self,
        systemprompt: &windows_core::HSTRING,
    ) -> windows_core::Result<LanguageModelContext> {
        let this = &windows_core::Interface::cast::<ILanguageModel2>(self)?;
        unsafe {
            let mut result__ = core::mem::zeroed();
            (windows_core::Interface::vtable(this).CreateContext2)(
                windows_core::Interface::as_raw(this),
                core::mem::transmute_copy(systemprompt),
                &mut result__,
            )
            .and_then(|| windows_core::Type::from_abi(result__))
        }
    }
    pub fn GetReadyState() -> windows_core::Result<AIFeatureReadyState> {
        Self::ILanguageModelStatics(|this| unsafe {
            let mut result__ = core::mem::zeroed();
            (windows_core::Interface::vtable(this).GetReadyState)(
                windows_core::Interface::as_raw(this),
                &mut result__,
            )
            .map(|| result__)
        })
    }
    pub fn EnsureReadyAsync(
    ) -> windows_core::Result<windows_future::IAsyncOperationWithProgress<AIFeatureReadyResult, f64>>
    {
        Self::ILanguageModelStatics(|this| unsafe {
            let mut result__ = core::mem::zeroed();
            (windows_core::Interface::vtable(this).EnsureReadyAsync)(
                windows_core::Interface::as_raw(this),
                &mut result__,
            )
            .and_then(|| windows_core::Type::from_abi(result__))
        })
    }
    pub fn CreateAsync() -> windows_core::Result<windows_future::IAsyncOperation<LanguageModel>> {
        Self::ILanguageModelStatics(|this| unsafe {
            let mut result__ = core::mem::zeroed();
            (windows_core::Interface::vtable(this).CreateAsync)(
                windows_core::Interface::as_raw(this),
                &mut result__,
            )
            .and_then(|| windows_core::Type::from_abi(result__))
        })
    }
    fn ILanguageModelStatics<R, F: FnOnce(&ILanguageModelStatics) -> windows_core::Result<R>>(
        callback: F,
    ) -> windows_core::Result<R> {
        static SHARED: windows_core::imp::FactoryCache<LanguageModel, ILanguageModelStatics> =
            windows_core::imp::FactoryCache::new();
        SHARED.call(callback)
    }
}
impl windows_core::RuntimeType for LanguageModel {
    const SIGNATURE: windows_core::imp::ConstBuffer =
        windows_core::imp::ConstBuffer::for_class::<Self, ILanguageModel>();
}
unsafe impl windows_core::Interface for LanguageModel {
    type Vtable = <ILanguageModel as windows_core::Interface>::Vtable;
    const IID: windows_core::GUID = <ILanguageModel as windows_core::Interface>::IID;
}
impl windows_core::RuntimeName for LanguageModel {
    const NAME: &'static str = "Microsoft.Windows.AI.Text.LanguageModel";
}
unsafe impl Send for LanguageModel {}
unsafe impl Sync for LanguageModel {}
#[repr(transparent)]
#[derive(Clone, Debug, Eq, PartialEq)]
pub struct LanguageModelContext(windows_core::IUnknown);
windows_core::imp::interface_hierarchy!(
    LanguageModelContext,
    windows_core::IUnknown,
    windows_core::IInspectable
);
windows_core::imp::required_hierarchy!(LanguageModelContext, IClosable);
impl LanguageModelContext {
    pub fn Close(&self) -> windows_core::Result<()> {
        let this = &windows_core::Interface::cast::<IClosable>(self)?;
        unsafe {
            (windows_core::Interface::vtable(this).Close)(windows_core::Interface::as_raw(this))
                .ok()
        }
    }
}
impl windows_core::RuntimeType for LanguageModelContext {
    const SIGNATURE: windows_core::imp::ConstBuffer =
        windows_core::imp::ConstBuffer::for_class::<Self, ILanguageModelContext>();
}
unsafe impl windows_core::Interface for LanguageModelContext {
    type Vtable = <ILanguageModelContext as windows_core::Interface>::Vtable;
    const IID: windows_core::GUID = <ILanguageModelContext as windows_core::Interface>::IID;
}
impl windows_core::RuntimeName for LanguageModelContext {
    const NAME: &'static str = "Microsoft.Windows.AI.Text.LanguageModelContext";
}
unsafe impl Send for LanguageModelContext {}
unsafe impl Sync for LanguageModelContext {}
#[repr(transparent)]
#[derive(Clone, Debug, Eq, PartialEq)]
pub struct LanguageModelEmbeddingVectorResult(windows_core::IUnknown);
windows_core::imp::interface_hierarchy!(
    LanguageModelEmbeddingVectorResult,
    windows_core::IUnknown,
    windows_core::IInspectable
);
impl LanguageModelEmbeddingVectorResult {
    pub fn Status(&self) -> windows_core::Result<LanguageModelResponseStatus> {
        let this = self;
        unsafe {
            let mut result__ = core::mem::zeroed();
            (windows_core::Interface::vtable(this).Status)(
                windows_core::Interface::as_raw(this),
                &mut result__,
            )
            .map(|| result__)
        }
    }
    pub fn ExtendedError(&self) -> windows_core::Result<windows_core::HRESULT> {
        let this = self;
        unsafe {
            let mut result__ = core::mem::zeroed();
            (windows_core::Interface::vtable(this).ExtendedError)(
                windows_core::Interface::as_raw(this),
                &mut result__,
            )
            .map(|| result__)
        }
    }
}
impl windows_core::RuntimeType for LanguageModelEmbeddingVectorResult {
    const SIGNATURE: windows_core::imp::ConstBuffer =
        windows_core::imp::ConstBuffer::for_class::<Self, ILanguageModelEmbeddingVectorResult>();
}
unsafe impl windows_core::Interface for LanguageModelEmbeddingVectorResult {
    type Vtable = <ILanguageModelEmbeddingVectorResult as windows_core::Interface>::Vtable;
    const IID: windows_core::GUID =
        <ILanguageModelEmbeddingVectorResult as windows_core::Interface>::IID;
}
impl windows_core::RuntimeName for LanguageModelEmbeddingVectorResult {
    const NAME: &'static str = "Microsoft.Windows.AI.Text.LanguageModelEmbeddingVectorResult";
}
unsafe impl Send for LanguageModelEmbeddingVectorResult {}
unsafe impl Sync for LanguageModelEmbeddingVectorResult {}
#[repr(transparent)]
#[derive(Clone, Debug, Eq, PartialEq)]
pub struct LanguageModelOptions(windows_core::IUnknown);
windows_core::imp::interface_hierarchy!(
    LanguageModelOptions,
    windows_core::IUnknown,
    windows_core::IInspectable
);
impl LanguageModelOptions {
    pub fn new() -> windows_core::Result<Self> {
        Self::IActivationFactory(|f| f.ActivateInstance::<Self>())
    }
    fn IActivationFactory<
        R,
        F: FnOnce(&windows_core::imp::IGenericFactory) -> windows_core::Result<R>,
    >(
        callback: F,
    ) -> windows_core::Result<R> {
        static SHARED: windows_core::imp::FactoryCache<
            LanguageModelOptions,
            windows_core::imp::IGenericFactory,
        > = windows_core::imp::FactoryCache::new();
        SHARED.call(callback)
    }
    pub fn Temperature(&self) -> windows_core::Result<f32> {
        let this = self;
        unsafe {
            let mut result__ = core::mem::zeroed();
            (windows_core::Interface::vtable(this).Temperature)(
                windows_core::Interface::as_raw(this),
                &mut result__,
            )
            .map(|| result__)
        }
    }
    pub fn SetTemperature(&self, value: f32) -> windows_core::Result<()> {
        let this = self;
        unsafe {
            (windows_core::Interface::vtable(this).SetTemperature)(
                windows_core::Interface::as_raw(this),
                value,
            )
            .ok()
        }
    }
    pub fn TopP(&self) -> windows_core::Result<f32> {
        let this = self;
        unsafe {
            let mut result__ = core::mem::zeroed();
            (windows_core::Interface::vtable(this).TopP)(
                windows_core::Interface::as_raw(this),
                &mut result__,
            )
            .map(|| result__)
        }
    }
    pub fn SetTopP(&self, value: f32) -> windows_core::Result<()> {
        let this = self;
        unsafe {
            (windows_core::Interface::vtable(this).SetTopP)(
                windows_core::Interface::as_raw(this),
                value,
            )
            .ok()
        }
    }
    pub fn TopK(&self) -> windows_core::Result<u32> {
        let this = self;
        unsafe {
            let mut result__ = core::mem::zeroed();
            (windows_core::Interface::vtable(this).TopK)(
                windows_core::Interface::as_raw(this),
                &mut result__,
            )
            .map(|| result__)
        }
    }
    pub fn SetTopK(&self, value: u32) -> windows_core::Result<()> {
        let this = self;
        unsafe {
            (windows_core::Interface::vtable(this).SetTopK)(
                windows_core::Interface::as_raw(this),
                value,
            )
            .ok()
        }
    }
}
impl windows_core::RuntimeType for LanguageModelOptions {
    const SIGNATURE: windows_core::imp::ConstBuffer =
        windows_core::imp::ConstBuffer::for_class::<Self, ILanguageModelOptions>();
}
unsafe impl windows_core::Interface for LanguageModelOptions {
    type Vtable = <ILanguageModelOptions as windows_core::Interface>::Vtable;
    const IID: windows_core::GUID = <ILanguageModelOptions as windows_core::Interface>::IID;
}
impl windows_core::RuntimeName for LanguageModelOptions {
    const NAME: &'static str = "Microsoft.Windows.AI.Text.LanguageModelOptions";
}
unsafe impl Send for LanguageModelOptions {}
unsafe impl Sync for LanguageModelOptions {}
#[repr(transparent)]
#[derive(Clone, Debug, Eq, PartialEq)]
pub struct LanguageModelResponseResult(windows_core::IUnknown);
windows_core::imp::interface_hierarchy!(
    LanguageModelResponseResult,
    windows_core::IUnknown,
    windows_core::IInspectable
);
impl LanguageModelResponseResult {
    pub fn Text(&self) -> windows_core::Result<windows_core::HSTRING> {
        let this = self;
        unsafe {
            let mut result__ = core::mem::zeroed();
            (windows_core::Interface::vtable(this).Text)(
                windows_core::Interface::as_raw(this),
                &mut result__,
            )
            .map(|| core::mem::transmute(result__))
        }
    }
    pub fn Status(&self) -> windows_core::Result<LanguageModelResponseStatus> {
        let this = self;
        unsafe {
            let mut result__ = core::mem::zeroed();
            (windows_core::Interface::vtable(this).Status)(
                windows_core::Interface::as_raw(this),
                &mut result__,
            )
            .map(|| result__)
        }
    }
    pub fn ExtendedError(&self) -> windows_core::Result<windows_core::HRESULT> {
        let this = self;
        unsafe {
            let mut result__ = core::mem::zeroed();
            (windows_core::Interface::vtable(this).ExtendedError)(
                windows_core::Interface::as_raw(this),
                &mut result__,
            )
            .map(|| result__)
        }
    }
}
impl windows_core::RuntimeType for LanguageModelResponseResult {
    const SIGNATURE: windows_core::imp::ConstBuffer =
        windows_core::imp::ConstBuffer::for_class::<Self, ILanguageModelResponseResult>();
}
unsafe impl windows_core::Interface for LanguageModelResponseResult {
    type Vtable = <ILanguageModelResponseResult as windows_core::Interface>::Vtable;
    const IID: windows_core::GUID = <ILanguageModelResponseResult as windows_core::Interface>::IID;
}
impl windows_core::RuntimeName for LanguageModelResponseResult {
    const NAME: &'static str = "Microsoft.Windows.AI.Text.LanguageModelResponseResult";
}
unsafe impl Send for LanguageModelResponseResult {}
unsafe impl Sync for LanguageModelResponseResult {}
#[repr(transparent)]
#[derive(Clone, Copy, Debug, Default, Eq, PartialEq)]
pub struct LanguageModelResponseStatus(pub i32);
impl LanguageModelResponseStatus {
    pub const Complete: Self = Self(0i32);
    pub const InProgress: Self = Self(1i32);
    pub const BlockedByPolicy: Self = Self(2i32);
    pub const PromptLargerThanContext: Self = Self(3i32);
    pub const PromptBlockedByContentModeration: Self = Self(4i32);
    pub const ResponseBlockedByContentModeration: Self = Self(5i32);
    pub const Error: Self = Self(6i32);
}
impl windows_core::TypeKind for LanguageModelResponseStatus {
    type TypeKind = windows_core::CopyType;
}
impl windows_core::RuntimeType for LanguageModelResponseStatus {
    const SIGNATURE: windows_core::imp::ConstBuffer = windows_core::imp::ConstBuffer::from_slice(
        b"enum(Microsoft.Windows.AI.Text.LanguageModelResponseStatus;i4)",
    );
}
#[repr(transparent)]
#[derive(Clone, Copy, Debug, Default, Eq, PartialEq)]
pub struct TextRewriteTone(pub i32);
impl TextRewriteTone {
    pub const Default: Self = Self(0i32);
    pub const General: Self = Self(1i32);
    pub const Casual: Self = Self(2i32);
    pub const Concise: Self = Self(3i32);
    pub const Formal: Self = Self(4i32);
}
impl windows_core::TypeKind for TextRewriteTone {
    type TypeKind = windows_core::CopyType;
}
impl windows_core::RuntimeType for TextRewriteTone {
    const SIGNATURE: windows_core::imp::ConstBuffer = windows_core::imp::ConstBuffer::from_slice(
        b"enum(Microsoft.Windows.AI.Text.TextRewriteTone;i4)",
    );
}
#[repr(transparent)]
#[derive(Clone, Debug, Eq, PartialEq)]
pub struct TextRewriter(windows_core::IUnknown);
windows_core::imp::interface_hierarchy!(
    TextRewriter,
    windows_core::IUnknown,
    windows_core::IInspectable
);
impl TextRewriter {
    pub fn RewriteAsync(
        &self,
        text: &windows_core::HSTRING,
    ) -> windows_core::Result<
        windows_future::IAsyncOperationWithProgress<
            LanguageModelResponseResult,
            windows_core::HSTRING,
        >,
    > {
        let this = self;
        unsafe {
            let mut result__ = core::mem::zeroed();
            (windows_core::Interface::vtable(this).RewriteAsync)(
                windows_core::Interface::as_raw(this),
                core::mem::transmute_copy(text),
                &mut result__,
            )
            .and_then(|| windows_core::Type::from_abi(result__))
        }
    }
    pub fn RewriteAsync2(
        &self,
        text: &windows_core::HSTRING,
        tone: TextRewriteTone,
    ) -> windows_core::Result<
        windows_future::IAsyncOperationWithProgress<
            LanguageModelResponseResult,
            windows_core::HSTRING,
        >,
    > {
        let this = &windows_core::Interface::cast::<ITextRewriter2>(self)?;
        unsafe {
            let mut result__ = core::mem::zeroed();
            (windows_core::Interface::vtable(this).RewriteAsync)(
                windows_core::Interface::as_raw(this),
                core::mem::transmute_copy(text),
                tone,
                &mut result__,
            )
            .and_then(|| windows_core::Type::from_abi(result__))
        }
    }
    pub fn RewriteCustomAsync(
        &self,
        text: &windows_core::HSTRING,
        customtone: &windows_core::HSTRING,
    ) -> windows_core::Result<
        windows_future::IAsyncOperationWithProgress<
            LanguageModelResponseResult,
            windows_core::HSTRING,
        >,
    > {
        let this = &windows_core::Interface::cast::<ITextRewriter3>(self)?;
        unsafe {
            let mut result__ = core::mem::zeroed();
            (windows_core::Interface::vtable(this).RewriteCustomAsync)(
                windows_core::Interface::as_raw(this),
                core::mem::transmute_copy(text),
                core::mem::transmute_copy(customtone),
                &mut result__,
            )
            .and_then(|| windows_core::Type::from_abi(result__))
        }
    }
    pub fn CreateInstance<P0>(languagemodel: P0) -> windows_core::Result<TextRewriter>
    where
        P0: windows_core::Param<LanguageModel>,
    {
        Self::ITextRewriterFactory(|this| unsafe {
            let mut result__ = core::mem::zeroed();
            (windows_core::Interface::vtable(this).CreateInstance)(
                windows_core::Interface::as_raw(this),
                languagemodel.param().abi(),
                &mut result__,
            )
            .and_then(|| windows_core::Type::from_abi(result__))
        })
    }
    fn ITextRewriterFactory<R, F: FnOnce(&ITextRewriterFactory) -> windows_core::Result<R>>(
        callback: F,
    ) -> windows_core::Result<R> {
        static SHARED: windows_core::imp::FactoryCache<TextRewriter, ITextRewriterFactory> =
            windows_core::imp::FactoryCache::new();
        SHARED.call(callback)
    }
}
impl windows_core::RuntimeType for TextRewriter {
    const SIGNATURE: windows_core::imp::ConstBuffer =
        windows_core::imp::ConstBuffer::for_class::<Self, ITextRewriter>();
}
unsafe impl windows_core::Interface for TextRewriter {
    type Vtable = <ITextRewriter as windows_core::Interface>::Vtable;
    const IID: windows_core::GUID = <ITextRewriter as windows_core::Interface>::IID;
}
impl windows_core::RuntimeName for TextRewriter {
    const NAME: &'static str = "Microsoft.Windows.AI.Text.TextRewriter";
}
unsafe impl Send for TextRewriter {}
unsafe impl Sync for TextRewriter {}
#[repr(transparent)]
#[derive(Clone, Debug, Eq, PartialEq)]
pub struct TextSummarizer(windows_core::IUnknown);
windows_core::imp::interface_hierarchy!(
    TextSummarizer,
    windows_core::IUnknown,
    windows_core::IInspectable
);
impl TextSummarizer {
    pub fn SummarizeAsync(
        &self,
        text: &windows_core::HSTRING,
    ) -> windows_core::Result<
        windows_future::IAsyncOperationWithProgress<
            LanguageModelResponseResult,
            windows_core::HSTRING,
        >,
    > {
        let this = self;
        unsafe {
            let mut result__ = core::mem::zeroed();
            (windows_core::Interface::vtable(this).SummarizeAsync)(
                windows_core::Interface::as_raw(this),
                core::mem::transmute_copy(text),
                &mut result__,
            )
            .and_then(|| windows_core::Type::from_abi(result__))
        }
    }
    pub fn SummarizeParagraphAsync(
        &self,
        text: &windows_core::HSTRING,
    ) -> windows_core::Result<
        windows_future::IAsyncOperationWithProgress<
            LanguageModelResponseResult,
            windows_core::HSTRING,
        >,
    > {
        let this = self;
        unsafe {
            let mut result__ = core::mem::zeroed();
            (windows_core::Interface::vtable(this).SummarizeParagraphAsync)(
                windows_core::Interface::as_raw(this),
                core::mem::transmute_copy(text),
                &mut result__,
            )
            .and_then(|| windows_core::Type::from_abi(result__))
        }
    }
    pub fn SummarizeConversationAsync<P0, P1>(
        &self,
        messages: P0,
        options: P1,
    ) -> windows_core::Result<
        windows_future::IAsyncOperationWithProgress<
            LanguageModelResponseResult,
            windows_core::HSTRING,
        >,
    >
    where
        P0: windows_core::Param<windows_collections::IVectorView<ConversationItem>>,
        P1: windows_core::Param<ConversationSummaryOptions>,
    {
        let this = &windows_core::Interface::cast::<ITextSummarizer2>(self)?;
        unsafe {
            let mut result__ = core::mem::zeroed();
            (windows_core::Interface::vtable(this).SummarizeConversationAsync)(
                windows_core::Interface::as_raw(this),
                messages.param().abi(),
                options.param().abi(),
                &mut result__,
            )
            .and_then(|| windows_core::Type::from_abi(result__))
        }
    }
    pub fn IsPromptLargerThanContext<P1>(
        &self,
        messages: &[Option<ConversationItem>],
        options: P1,
        cutoffposition: &mut u64,
    ) -> windows_core::Result<bool>
    where
        P1: windows_core::Param<ConversationSummaryOptions>,
    {
        let this = &windows_core::Interface::cast::<ITextSummarizer3>(self)?;
        unsafe {
            let mut result__ = core::mem::zeroed();
            (windows_core::Interface::vtable(this).IsPromptLargerThanContext)(
                windows_core::Interface::as_raw(this),
                messages.len().try_into().unwrap(),
                core::mem::transmute(messages.as_ptr()),
                options.param().abi(),
                cutoffposition,
                &mut result__,
            )
            .map(|| result__)
        }
    }
    pub fn IsPromptLargerThanContext2(
        &self,
        text: &windows_core::HSTRING,
        cutoffposition: &mut u64,
    ) -> windows_core::Result<bool> {
        let this = &windows_core::Interface::cast::<ITextSummarizer4>(self)?;
        unsafe {
            let mut result__ = core::mem::zeroed();
            (windows_core::Interface::vtable(this).IsPromptLargerThanContext)(
                windows_core::Interface::as_raw(this),
                core::mem::transmute_copy(text),
                cutoffposition,
                &mut result__,
            )
            .map(|| result__)
        }
    }
    pub fn CreateInstance<P0>(languagemodel: P0) -> windows_core::Result<TextSummarizer>
    where
        P0: windows_core::Param<LanguageModel>,
    {
        Self::ITextSummarizerFactory(|this| unsafe {
            let mut result__ = core::mem::zeroed();
            (windows_core::Interface::vtable(this).CreateInstance)(
                windows_core::Interface::as_raw(this),
                languagemodel.param().abi(),
                &mut result__,
            )
            .and_then(|| windows_core::Type::from_abi(result__))
        })
    }
    fn ITextSummarizerFactory<R, F: FnOnce(&ITextSummarizerFactory) -> windows_core::Result<R>>(
        callback: F,
    ) -> windows_core::Result<R> {
        static SHARED: windows_core::imp::FactoryCache<TextSummarizer, ITextSummarizerFactory> =
            windows_core::imp::FactoryCache::new();
        SHARED.call(callback)
    }
}
impl windows_core::RuntimeType for TextSummarizer {
    const SIGNATURE: windows_core::imp::ConstBuffer =
        windows_core::imp::ConstBuffer::for_class::<Self, ITextSummarizer>();
}
unsafe impl windows_core::Interface for TextSummarizer {
    type Vtable = <ITextSummarizer as windows_core::Interface>::Vtable;
    const IID: windows_core::GUID = <ITextSummarizer as windows_core::Interface>::IID;
}
impl windows_core::RuntimeName for TextSummarizer {
    const NAME: &'static str = "Microsoft.Windows.AI.Text.TextSummarizer";
}
unsafe impl Send for TextSummarizer {}
unsafe impl Sync for TextSummarizer {}
#[repr(transparent)]
#[derive(Clone, Debug, Eq, PartialEq)]
pub struct TextToTableConverter(windows_core::IUnknown);
windows_core::imp::interface_hierarchy!(
    TextToTableConverter,
    windows_core::IUnknown,
    windows_core::IInspectable
);
impl TextToTableConverter {
    pub fn ConvertAsync(
        &self,
        text: &windows_core::HSTRING,
    ) -> windows_core::Result<
        windows_future::IAsyncOperationWithProgress<
            TextToTableResponseResult,
            windows_core::HSTRING,
        >,
    > {
        let this = self;
        unsafe {
            let mut result__ = core::mem::zeroed();
            (windows_core::Interface::vtable(this).ConvertAsync)(
                windows_core::Interface::as_raw(this),
                core::mem::transmute_copy(text),
                &mut result__,
            )
            .and_then(|| windows_core::Type::from_abi(result__))
        }
    }
    pub fn CreateInstance<P0>(languagemodel: P0) -> windows_core::Result<TextToTableConverter>
    where
        P0: windows_core::Param<LanguageModel>,
    {
        Self::ITextToTableConverterFactory(|this| unsafe {
            let mut result__ = core::mem::zeroed();
            (windows_core::Interface::vtable(this).CreateInstance)(
                windows_core::Interface::as_raw(this),
                languagemodel.param().abi(),
                &mut result__,
            )
            .and_then(|| windows_core::Type::from_abi(result__))
        })
    }
    fn ITextToTableConverterFactory<
        R,
        F: FnOnce(&ITextToTableConverterFactory) -> windows_core::Result<R>,
    >(
        callback: F,
    ) -> windows_core::Result<R> {
        static SHARED: windows_core::imp::FactoryCache<
            TextToTableConverter,
            ITextToTableConverterFactory,
        > = windows_core::imp::FactoryCache::new();
        SHARED.call(callback)
    }
}
impl windows_core::RuntimeType for TextToTableConverter {
    const SIGNATURE: windows_core::imp::ConstBuffer =
        windows_core::imp::ConstBuffer::for_class::<Self, ITextToTableConverter>();
}
unsafe impl windows_core::Interface for TextToTableConverter {
    type Vtable = <ITextToTableConverter as windows_core::Interface>::Vtable;
    const IID: windows_core::GUID = <ITextToTableConverter as windows_core::Interface>::IID;
}
impl windows_core::RuntimeName for TextToTableConverter {
    const NAME: &'static str = "Microsoft.Windows.AI.Text.TextToTableConverter";
}
unsafe impl Send for TextToTableConverter {}
unsafe impl Sync for TextToTableConverter {}
#[repr(transparent)]
#[derive(Clone, Debug, Eq, PartialEq)]
pub struct TextToTableResponseResult(windows_core::IUnknown);
windows_core::imp::interface_hierarchy!(
    TextToTableResponseResult,
    windows_core::IUnknown,
    windows_core::IInspectable
);
impl TextToTableResponseResult {
    pub fn GetRows(&self) -> windows_core::Result<windows_core::Array<TextToTableRow>> {
        let this = self;
        unsafe {
            let mut result__ = core::mem::MaybeUninit::zeroed();
            (windows_core::Interface::vtable(this).GetRows)(
                windows_core::Interface::as_raw(this),
                windows_core::Array::<TextToTableRow>::set_abi_len(core::mem::transmute(
                    &mut result__,
                )),
                result__.as_mut_ptr() as *mut _ as _,
            )
            .map(|| result__.assume_init())
        }
    }
    pub fn Status(&self) -> windows_core::Result<LanguageModelResponseStatus> {
        let this = self;
        unsafe {
            let mut result__ = core::mem::zeroed();
            (windows_core::Interface::vtable(this).Status)(
                windows_core::Interface::as_raw(this),
                &mut result__,
            )
            .map(|| result__)
        }
    }
    pub fn ExtendedError(&self) -> windows_core::Result<windows_core::HRESULT> {
        let this = self;
        unsafe {
            let mut result__ = core::mem::zeroed();
            (windows_core::Interface::vtable(this).ExtendedError)(
                windows_core::Interface::as_raw(this),
                &mut result__,
            )
            .map(|| result__)
        }
    }
}
impl windows_core::RuntimeType for TextToTableResponseResult {
    const SIGNATURE: windows_core::imp::ConstBuffer =
        windows_core::imp::ConstBuffer::for_class::<Self, ITextToTableResponseResult>();
}
unsafe impl windows_core::Interface for TextToTableResponseResult {
    type Vtable = <ITextToTableResponseResult as windows_core::Interface>::Vtable;
    const IID: windows_core::GUID = <ITextToTableResponseResult as windows_core::Interface>::IID;
}
impl windows_core::RuntimeName for TextToTableResponseResult {
    const NAME: &'static str = "Microsoft.Windows.AI.Text.TextToTableResponseResult";
}
unsafe impl Send for TextToTableResponseResult {}
unsafe impl Sync for TextToTableResponseResult {}
#[repr(transparent)]
#[derive(Clone, Debug, Eq, PartialEq)]
pub struct TextToTableRow(windows_core::IUnknown);
windows_core::imp::interface_hierarchy!(
    TextToTableRow,
    windows_core::IUnknown,
    windows_core::IInspectable
);
impl TextToTableRow {
    pub fn GetColumns(&self) -> windows_core::Result<windows_core::Array<windows_core::HSTRING>> {
        let this = self;
        unsafe {
            let mut result__ = core::mem::MaybeUninit::zeroed();
            (windows_core::Interface::vtable(this).GetColumns)(
                windows_core::Interface::as_raw(this),
                windows_core::Array::<windows_core::HSTRING>::set_abi_len(core::mem::transmute(
                    &mut result__,
                )),
                result__.as_mut_ptr() as *mut _ as _,
            )
            .map(|| result__.assume_init())
        }
    }
}
impl windows_core::RuntimeType for TextToTableRow {
    const SIGNATURE: windows_core::imp::ConstBuffer =
        windows_core::imp::ConstBuffer::for_class::<Self, ITextToTableRow>();
}
unsafe impl windows_core::Interface for TextToTableRow {
    type Vtable = <ITextToTableRow as windows_core::Interface>::Vtable;
    const IID: windows_core::GUID = <ITextToTableRow as windows_core::Interface>::IID;
}
impl windows_core::RuntimeName for TextToTableRow {
    const NAME: &'static str = "Microsoft.Windows.AI.Text.TextToTableRow";
}
unsafe impl Send for TextToTableRow {}
unsafe impl Sync for TextToTableRow {}
